// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module L1Cache2L2Arbiter(	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  output        io_memReqVecIn_0_ready,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input         io_memReqVecIn_0_valid,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input  [31:0] io_memReqVecIn_0_bits_a_addr,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_0_bits_spike_info_vaddr,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input  [12:0] io_memReqVecIn_0_bits_a_source,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output        io_memReqVecIn_1_ready,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input         io_memReqVecIn_1_valid,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input  [2:0]  io_memReqVecIn_1_bits_a_opcode,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_param,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input  [31:0] io_memReqVecIn_1_bits_a_addr,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_0,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_1,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_2,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_3,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_4,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_5,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_6,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_7,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_8,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_9,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_10,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_11,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_12,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_13,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_14,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_15,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_16,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_17,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_18,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_19,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_20,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_21,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_22,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_23,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_24,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_25,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_26,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_27,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_28,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_29,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_30,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_data_31,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input  [3:0]  io_memReqVecIn_1_bits_a_mask_0,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_1,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_2,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_3,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_4,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_5,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_6,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_7,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_8,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_9,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_10,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_11,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_12,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_13,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_14,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_15,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_16,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_17,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_18,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_19,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_20,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_21,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_22,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_23,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_24,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_25,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_26,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_27,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_28,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_29,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_30,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_a_mask_31,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input  [31:0] io_memReqVecIn_1_bits_spike_info_pc,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqVecIn_1_bits_spike_info_vaddr,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input  [12:0] io_memReqVecIn_1_bits_a_source,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input         io_memReqOut_ready,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output        io_memReqOut_valid,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output [2:0]  io_memReqOut_bits_a_opcode,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_param,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output [13:0] io_memReqOut_bits_a_source,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output [31:0] io_memReqOut_bits_a_addr,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_0,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_1,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_2,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_3,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_4,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_5,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_6,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_7,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_8,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_9,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_10,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_11,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_12,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_13,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_14,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_15,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_16,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_17,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_18,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_19,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_20,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_21,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_22,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_23,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_24,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_25,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_26,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_27,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_28,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_29,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_30,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_data_31,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output [3:0]  io_memReqOut_bits_a_mask_0,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_1,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_2,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_3,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_4,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_5,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_6,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_7,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_8,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_9,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_10,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_11,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_12,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_13,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_14,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_15,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_16,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_17,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_18,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_19,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_20,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_21,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_22,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_23,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_24,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_25,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_26,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_27,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_28,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_29,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_30,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_a_mask_31,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output [31:0] io_memReqOut_bits_spike_info_pc,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memReqOut_bits_spike_info_vaddr,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output        io_memRspIn_ready,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input         io_memRspIn_valid,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input  [2:0]  io_memRspIn_bits_d_opcode,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input  [31:0] io_memRspIn_bits_d_addr,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_0,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_1,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_2,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_3,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_4,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_5,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_6,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_7,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_8,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_9,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_10,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_11,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_12,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_13,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_14,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_15,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_16,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_17,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_18,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_19,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_20,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_21,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_22,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_23,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_24,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_25,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_26,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_27,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_28,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_29,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_30,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspIn_bits_d_data_31,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input  [13:0] io_memRspIn_bits_d_source,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input         io_memRspVecOut_0_ready,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output        io_memRspVecOut_0_valid,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output [12:0] io_memRspVecOut_0_bits_d_source,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output [31:0] io_memRspVecOut_0_bits_d_addr,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_0,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_1,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_2,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_3,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_4,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_5,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_6,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_7,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_8,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_9,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_10,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_11,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_12,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_13,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_14,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_15,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_16,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_17,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_18,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_19,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_20,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_21,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_22,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_23,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_24,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_25,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_26,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_27,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_28,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_29,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_30,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_0_bits_d_data_31,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  input         io_memRspVecOut_1_ready,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output        io_memRspVecOut_1_valid,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output [2:0]  io_memRspVecOut_1_bits_d_opcode,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output [12:0] io_memRspVecOut_1_bits_d_source,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
  output [31:0] io_memRspVecOut_1_bits_d_addr,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_0,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_1,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_2,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_3,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_4,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_5,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_6,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_7,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_8,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_9,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_10,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_11,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_12,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_13,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_14,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_15,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_16,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_17,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_18,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_19,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_20,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_21,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_22,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_23,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_24,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_25,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_26,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_27,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_28,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_29,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_30,	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
                io_memRspVecOut_1_bits_d_data_31	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:29:14
);

  wire [31:0] _memReqArb_io_out_bits_a_source;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:32:25
  Arbiter2_L1CacheMemReq memReqArb (	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:32:25
    .io_in_0_ready                 (io_memReqVecIn_0_ready),
    .io_in_0_valid                 (io_memReqVecIn_0_valid),
    .io_in_0_bits_a_source         ({19'h0, io_memReqVecIn_0_bits_a_source}),	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:35:38
    .io_in_0_bits_a_addr           (io_memReqVecIn_0_bits_a_addr),
    .io_in_0_bits_spike_info_vaddr (io_memReqVecIn_0_bits_spike_info_vaddr),
    .io_in_1_ready                 (io_memReqVecIn_1_ready),
    .io_in_1_valid                 (io_memReqVecIn_1_valid),
    .io_in_1_bits_a_opcode         (io_memReqVecIn_1_bits_a_opcode),
    .io_in_1_bits_a_param          (io_memReqVecIn_1_bits_a_param),
    .io_in_1_bits_a_source         ({19'h1, io_memReqVecIn_1_bits_a_source}),	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:35:38
    .io_in_1_bits_a_addr           (io_memReqVecIn_1_bits_a_addr),
    .io_in_1_bits_a_data_0         (io_memReqVecIn_1_bits_a_data_0),
    .io_in_1_bits_a_data_1         (io_memReqVecIn_1_bits_a_data_1),
    .io_in_1_bits_a_data_2         (io_memReqVecIn_1_bits_a_data_2),
    .io_in_1_bits_a_data_3         (io_memReqVecIn_1_bits_a_data_3),
    .io_in_1_bits_a_data_4         (io_memReqVecIn_1_bits_a_data_4),
    .io_in_1_bits_a_data_5         (io_memReqVecIn_1_bits_a_data_5),
    .io_in_1_bits_a_data_6         (io_memReqVecIn_1_bits_a_data_6),
    .io_in_1_bits_a_data_7         (io_memReqVecIn_1_bits_a_data_7),
    .io_in_1_bits_a_data_8         (io_memReqVecIn_1_bits_a_data_8),
    .io_in_1_bits_a_data_9         (io_memReqVecIn_1_bits_a_data_9),
    .io_in_1_bits_a_data_10        (io_memReqVecIn_1_bits_a_data_10),
    .io_in_1_bits_a_data_11        (io_memReqVecIn_1_bits_a_data_11),
    .io_in_1_bits_a_data_12        (io_memReqVecIn_1_bits_a_data_12),
    .io_in_1_bits_a_data_13        (io_memReqVecIn_1_bits_a_data_13),
    .io_in_1_bits_a_data_14        (io_memReqVecIn_1_bits_a_data_14),
    .io_in_1_bits_a_data_15        (io_memReqVecIn_1_bits_a_data_15),
    .io_in_1_bits_a_data_16        (io_memReqVecIn_1_bits_a_data_16),
    .io_in_1_bits_a_data_17        (io_memReqVecIn_1_bits_a_data_17),
    .io_in_1_bits_a_data_18        (io_memReqVecIn_1_bits_a_data_18),
    .io_in_1_bits_a_data_19        (io_memReqVecIn_1_bits_a_data_19),
    .io_in_1_bits_a_data_20        (io_memReqVecIn_1_bits_a_data_20),
    .io_in_1_bits_a_data_21        (io_memReqVecIn_1_bits_a_data_21),
    .io_in_1_bits_a_data_22        (io_memReqVecIn_1_bits_a_data_22),
    .io_in_1_bits_a_data_23        (io_memReqVecIn_1_bits_a_data_23),
    .io_in_1_bits_a_data_24        (io_memReqVecIn_1_bits_a_data_24),
    .io_in_1_bits_a_data_25        (io_memReqVecIn_1_bits_a_data_25),
    .io_in_1_bits_a_data_26        (io_memReqVecIn_1_bits_a_data_26),
    .io_in_1_bits_a_data_27        (io_memReqVecIn_1_bits_a_data_27),
    .io_in_1_bits_a_data_28        (io_memReqVecIn_1_bits_a_data_28),
    .io_in_1_bits_a_data_29        (io_memReqVecIn_1_bits_a_data_29),
    .io_in_1_bits_a_data_30        (io_memReqVecIn_1_bits_a_data_30),
    .io_in_1_bits_a_data_31        (io_memReqVecIn_1_bits_a_data_31),
    .io_in_1_bits_a_mask_0         (io_memReqVecIn_1_bits_a_mask_0),
    .io_in_1_bits_a_mask_1         (io_memReqVecIn_1_bits_a_mask_1),
    .io_in_1_bits_a_mask_2         (io_memReqVecIn_1_bits_a_mask_2),
    .io_in_1_bits_a_mask_3         (io_memReqVecIn_1_bits_a_mask_3),
    .io_in_1_bits_a_mask_4         (io_memReqVecIn_1_bits_a_mask_4),
    .io_in_1_bits_a_mask_5         (io_memReqVecIn_1_bits_a_mask_5),
    .io_in_1_bits_a_mask_6         (io_memReqVecIn_1_bits_a_mask_6),
    .io_in_1_bits_a_mask_7         (io_memReqVecIn_1_bits_a_mask_7),
    .io_in_1_bits_a_mask_8         (io_memReqVecIn_1_bits_a_mask_8),
    .io_in_1_bits_a_mask_9         (io_memReqVecIn_1_bits_a_mask_9),
    .io_in_1_bits_a_mask_10        (io_memReqVecIn_1_bits_a_mask_10),
    .io_in_1_bits_a_mask_11        (io_memReqVecIn_1_bits_a_mask_11),
    .io_in_1_bits_a_mask_12        (io_memReqVecIn_1_bits_a_mask_12),
    .io_in_1_bits_a_mask_13        (io_memReqVecIn_1_bits_a_mask_13),
    .io_in_1_bits_a_mask_14        (io_memReqVecIn_1_bits_a_mask_14),
    .io_in_1_bits_a_mask_15        (io_memReqVecIn_1_bits_a_mask_15),
    .io_in_1_bits_a_mask_16        (io_memReqVecIn_1_bits_a_mask_16),
    .io_in_1_bits_a_mask_17        (io_memReqVecIn_1_bits_a_mask_17),
    .io_in_1_bits_a_mask_18        (io_memReqVecIn_1_bits_a_mask_18),
    .io_in_1_bits_a_mask_19        (io_memReqVecIn_1_bits_a_mask_19),
    .io_in_1_bits_a_mask_20        (io_memReqVecIn_1_bits_a_mask_20),
    .io_in_1_bits_a_mask_21        (io_memReqVecIn_1_bits_a_mask_21),
    .io_in_1_bits_a_mask_22        (io_memReqVecIn_1_bits_a_mask_22),
    .io_in_1_bits_a_mask_23        (io_memReqVecIn_1_bits_a_mask_23),
    .io_in_1_bits_a_mask_24        (io_memReqVecIn_1_bits_a_mask_24),
    .io_in_1_bits_a_mask_25        (io_memReqVecIn_1_bits_a_mask_25),
    .io_in_1_bits_a_mask_26        (io_memReqVecIn_1_bits_a_mask_26),
    .io_in_1_bits_a_mask_27        (io_memReqVecIn_1_bits_a_mask_27),
    .io_in_1_bits_a_mask_28        (io_memReqVecIn_1_bits_a_mask_28),
    .io_in_1_bits_a_mask_29        (io_memReqVecIn_1_bits_a_mask_29),
    .io_in_1_bits_a_mask_30        (io_memReqVecIn_1_bits_a_mask_30),
    .io_in_1_bits_a_mask_31        (io_memReqVecIn_1_bits_a_mask_31),
    .io_in_1_bits_spike_info_pc    (io_memReqVecIn_1_bits_spike_info_pc),
    .io_in_1_bits_spike_info_vaddr (io_memReqVecIn_1_bits_spike_info_vaddr),
    .io_out_ready                  (io_memReqOut_ready),
    .io_out_valid                  (io_memReqOut_valid),
    .io_out_bits_a_opcode          (io_memReqOut_bits_a_opcode),
    .io_out_bits_a_param           (io_memReqOut_bits_a_param),
    .io_out_bits_a_source          (_memReqArb_io_out_bits_a_source),
    .io_out_bits_a_addr            (io_memReqOut_bits_a_addr),
    .io_out_bits_a_data_0          (io_memReqOut_bits_a_data_0),
    .io_out_bits_a_data_1          (io_memReqOut_bits_a_data_1),
    .io_out_bits_a_data_2          (io_memReqOut_bits_a_data_2),
    .io_out_bits_a_data_3          (io_memReqOut_bits_a_data_3),
    .io_out_bits_a_data_4          (io_memReqOut_bits_a_data_4),
    .io_out_bits_a_data_5          (io_memReqOut_bits_a_data_5),
    .io_out_bits_a_data_6          (io_memReqOut_bits_a_data_6),
    .io_out_bits_a_data_7          (io_memReqOut_bits_a_data_7),
    .io_out_bits_a_data_8          (io_memReqOut_bits_a_data_8),
    .io_out_bits_a_data_9          (io_memReqOut_bits_a_data_9),
    .io_out_bits_a_data_10         (io_memReqOut_bits_a_data_10),
    .io_out_bits_a_data_11         (io_memReqOut_bits_a_data_11),
    .io_out_bits_a_data_12         (io_memReqOut_bits_a_data_12),
    .io_out_bits_a_data_13         (io_memReqOut_bits_a_data_13),
    .io_out_bits_a_data_14         (io_memReqOut_bits_a_data_14),
    .io_out_bits_a_data_15         (io_memReqOut_bits_a_data_15),
    .io_out_bits_a_data_16         (io_memReqOut_bits_a_data_16),
    .io_out_bits_a_data_17         (io_memReqOut_bits_a_data_17),
    .io_out_bits_a_data_18         (io_memReqOut_bits_a_data_18),
    .io_out_bits_a_data_19         (io_memReqOut_bits_a_data_19),
    .io_out_bits_a_data_20         (io_memReqOut_bits_a_data_20),
    .io_out_bits_a_data_21         (io_memReqOut_bits_a_data_21),
    .io_out_bits_a_data_22         (io_memReqOut_bits_a_data_22),
    .io_out_bits_a_data_23         (io_memReqOut_bits_a_data_23),
    .io_out_bits_a_data_24         (io_memReqOut_bits_a_data_24),
    .io_out_bits_a_data_25         (io_memReqOut_bits_a_data_25),
    .io_out_bits_a_data_26         (io_memReqOut_bits_a_data_26),
    .io_out_bits_a_data_27         (io_memReqOut_bits_a_data_27),
    .io_out_bits_a_data_28         (io_memReqOut_bits_a_data_28),
    .io_out_bits_a_data_29         (io_memReqOut_bits_a_data_29),
    .io_out_bits_a_data_30         (io_memReqOut_bits_a_data_30),
    .io_out_bits_a_data_31         (io_memReqOut_bits_a_data_31),
    .io_out_bits_a_mask_0          (io_memReqOut_bits_a_mask_0),
    .io_out_bits_a_mask_1          (io_memReqOut_bits_a_mask_1),
    .io_out_bits_a_mask_2          (io_memReqOut_bits_a_mask_2),
    .io_out_bits_a_mask_3          (io_memReqOut_bits_a_mask_3),
    .io_out_bits_a_mask_4          (io_memReqOut_bits_a_mask_4),
    .io_out_bits_a_mask_5          (io_memReqOut_bits_a_mask_5),
    .io_out_bits_a_mask_6          (io_memReqOut_bits_a_mask_6),
    .io_out_bits_a_mask_7          (io_memReqOut_bits_a_mask_7),
    .io_out_bits_a_mask_8          (io_memReqOut_bits_a_mask_8),
    .io_out_bits_a_mask_9          (io_memReqOut_bits_a_mask_9),
    .io_out_bits_a_mask_10         (io_memReqOut_bits_a_mask_10),
    .io_out_bits_a_mask_11         (io_memReqOut_bits_a_mask_11),
    .io_out_bits_a_mask_12         (io_memReqOut_bits_a_mask_12),
    .io_out_bits_a_mask_13         (io_memReqOut_bits_a_mask_13),
    .io_out_bits_a_mask_14         (io_memReqOut_bits_a_mask_14),
    .io_out_bits_a_mask_15         (io_memReqOut_bits_a_mask_15),
    .io_out_bits_a_mask_16         (io_memReqOut_bits_a_mask_16),
    .io_out_bits_a_mask_17         (io_memReqOut_bits_a_mask_17),
    .io_out_bits_a_mask_18         (io_memReqOut_bits_a_mask_18),
    .io_out_bits_a_mask_19         (io_memReqOut_bits_a_mask_19),
    .io_out_bits_a_mask_20         (io_memReqOut_bits_a_mask_20),
    .io_out_bits_a_mask_21         (io_memReqOut_bits_a_mask_21),
    .io_out_bits_a_mask_22         (io_memReqOut_bits_a_mask_22),
    .io_out_bits_a_mask_23         (io_memReqOut_bits_a_mask_23),
    .io_out_bits_a_mask_24         (io_memReqOut_bits_a_mask_24),
    .io_out_bits_a_mask_25         (io_memReqOut_bits_a_mask_25),
    .io_out_bits_a_mask_26         (io_memReqOut_bits_a_mask_26),
    .io_out_bits_a_mask_27         (io_memReqOut_bits_a_mask_27),
    .io_out_bits_a_mask_28         (io_memReqOut_bits_a_mask_28),
    .io_out_bits_a_mask_29         (io_memReqOut_bits_a_mask_29),
    .io_out_bits_a_mask_30         (io_memReqOut_bits_a_mask_30),
    .io_out_bits_a_mask_31         (io_memReqOut_bits_a_mask_31),
    .io_out_bits_spike_info_pc     (io_memReqOut_bits_spike_info_pc),
    .io_out_bits_spike_info_vaddr  (io_memReqOut_bits_spike_info_vaddr)
  );
  assign io_memReqOut_bits_a_source = _memReqArb_io_out_bits_a_source[13:0];	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7, :32:25, :37:16
  assign io_memRspIn_ready =
    |(2'h1 << io_memRspIn_bits_d_source[13]
      & {io_memRspVecOut_1_ready, io_memRspVecOut_0_ready});	// src/main/scala/chisel3/util/Mux.scala:33:{47,53}, src/main/scala/chisel3/util/OneHot.scala:58:35, ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7, :44:32, :47:12
  assign io_memRspVecOut_0_valid = ~(io_memRspIn_bits_d_source[13]) & io_memRspIn_valid;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7, :44:{32,150,162}
  assign io_memRspVecOut_0_bits_d_source = io_memRspIn_bits_d_source[12:0];	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7, :42:29
  assign io_memRspVecOut_0_bits_d_addr = io_memRspIn_bits_d_addr;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_0 = io_memRspIn_bits_d_data_0;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_1 = io_memRspIn_bits_d_data_1;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_2 = io_memRspIn_bits_d_data_2;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_3 = io_memRspIn_bits_d_data_3;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_4 = io_memRspIn_bits_d_data_4;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_5 = io_memRspIn_bits_d_data_5;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_6 = io_memRspIn_bits_d_data_6;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_7 = io_memRspIn_bits_d_data_7;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_8 = io_memRspIn_bits_d_data_8;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_9 = io_memRspIn_bits_d_data_9;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_10 = io_memRspIn_bits_d_data_10;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_11 = io_memRspIn_bits_d_data_11;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_12 = io_memRspIn_bits_d_data_12;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_13 = io_memRspIn_bits_d_data_13;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_14 = io_memRspIn_bits_d_data_14;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_15 = io_memRspIn_bits_d_data_15;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_16 = io_memRspIn_bits_d_data_16;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_17 = io_memRspIn_bits_d_data_17;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_18 = io_memRspIn_bits_d_data_18;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_19 = io_memRspIn_bits_d_data_19;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_20 = io_memRspIn_bits_d_data_20;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_21 = io_memRspIn_bits_d_data_21;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_22 = io_memRspIn_bits_d_data_22;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_23 = io_memRspIn_bits_d_data_23;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_24 = io_memRspIn_bits_d_data_24;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_25 = io_memRspIn_bits_d_data_25;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_26 = io_memRspIn_bits_d_data_26;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_27 = io_memRspIn_bits_d_data_27;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_28 = io_memRspIn_bits_d_data_28;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_29 = io_memRspIn_bits_d_data_29;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_30 = io_memRspIn_bits_d_data_30;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_0_bits_d_data_31 = io_memRspIn_bits_d_data_31;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_valid = io_memRspIn_bits_d_source[13] & io_memRspIn_valid;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7, :44:{32,162}
  assign io_memRspVecOut_1_bits_d_opcode = io_memRspIn_bits_d_opcode;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_source = io_memRspIn_bits_d_source[12:0];	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7, :42:29
  assign io_memRspVecOut_1_bits_d_addr = io_memRspIn_bits_d_addr;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_0 = io_memRspIn_bits_d_data_0;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_1 = io_memRspIn_bits_d_data_1;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_2 = io_memRspIn_bits_d_data_2;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_3 = io_memRspIn_bits_d_data_3;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_4 = io_memRspIn_bits_d_data_4;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_5 = io_memRspIn_bits_d_data_5;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_6 = io_memRspIn_bits_d_data_6;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_7 = io_memRspIn_bits_d_data_7;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_8 = io_memRspIn_bits_d_data_8;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_9 = io_memRspIn_bits_d_data_9;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_10 = io_memRspIn_bits_d_data_10;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_11 = io_memRspIn_bits_d_data_11;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_12 = io_memRspIn_bits_d_data_12;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_13 = io_memRspIn_bits_d_data_13;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_14 = io_memRspIn_bits_d_data_14;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_15 = io_memRspIn_bits_d_data_15;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_16 = io_memRspIn_bits_d_data_16;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_17 = io_memRspIn_bits_d_data_17;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_18 = io_memRspIn_bits_d_data_18;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_19 = io_memRspIn_bits_d_data_19;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_20 = io_memRspIn_bits_d_data_20;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_21 = io_memRspIn_bits_d_data_21;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_22 = io_memRspIn_bits_d_data_22;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_23 = io_memRspIn_bits_d_data_23;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_24 = io_memRspIn_bits_d_data_24;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_25 = io_memRspIn_bits_d_data_25;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_26 = io_memRspIn_bits_d_data_26;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_27 = io_memRspIn_bits_d_data_27;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_28 = io_memRspIn_bits_d_data_28;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_29 = io_memRspIn_bits_d_data_29;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_30 = io_memRspIn_bits_d_data_30;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
  assign io_memRspVecOut_1_bits_d_data_31 = io_memRspIn_bits_d_data_31;	// ventus/src/L1Cache/L1Cache2L2Arbiter.scala:28:7
endmodule

