// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module CSRexe(	// ventus/src/pipeline/CSR.scala:320:7
  input         clock,	// ventus/src/pipeline/CSR.scala:320:7
                reset,	// ventus/src/pipeline/CSR.scala:320:7
  output        io_in_ready,	// ventus/src/pipeline/CSR.scala:321:14
  input         io_in_valid,	// ventus/src/pipeline/CSR.scala:321:14
  input  [31:0] io_in_bits_ctrl_inst,	// ventus/src/pipeline/CSR.scala:321:14
  input  [1:0]  io_in_bits_ctrl_wid,	// ventus/src/pipeline/CSR.scala:321:14
                io_in_bits_ctrl_csr,	// ventus/src/pipeline/CSR.scala:321:14
  input         io_in_bits_ctrl_isvec,	// ventus/src/pipeline/CSR.scala:321:14
                io_in_bits_ctrl_custom_signal_0,	// ventus/src/pipeline/CSR.scala:321:14
  input  [7:0]  io_in_bits_ctrl_reg_idxw,	// ventus/src/pipeline/CSR.scala:321:14
  input         io_in_bits_ctrl_wxd,	// ventus/src/pipeline/CSR.scala:321:14
  input  [7:0]  io_in_bits_ctrl_spike_info_sm_id,	// ventus/src/pipeline/CSR.scala:321:14
  input  [31:0] io_in_bits_ctrl_spike_info_pc,	// ventus/src/pipeline/CSR.scala:321:14
                io_in_bits_ctrl_spike_info_inst,	// ventus/src/pipeline/CSR.scala:321:14
                io_in_bits_in1,	// ventus/src/pipeline/CSR.scala:321:14
  input         io_out_ready,	// ventus/src/pipeline/CSR.scala:321:14
  output        io_out_valid,	// ventus/src/pipeline/CSR.scala:321:14
  output [31:0] io_out_bits_wb_wxd_rd,	// ventus/src/pipeline/CSR.scala:321:14
  output        io_out_bits_wxd,	// ventus/src/pipeline/CSR.scala:321:14
  output [7:0]  io_out_bits_reg_idxw,	// ventus/src/pipeline/CSR.scala:321:14
  output [1:0]  io_out_bits_warp_id,	// ventus/src/pipeline/CSR.scala:321:14
  output [7:0]  io_out_bits_spike_info_sm_id,	// ventus/src/pipeline/CSR.scala:321:14
  output [31:0] io_out_bits_spike_info_pc,	// ventus/src/pipeline/CSR.scala:321:14
                io_out_bits_spike_info_inst,	// ventus/src/pipeline/CSR.scala:321:14
  input  [1:0]  io_rm_wid_0,	// ventus/src/pipeline/CSR.scala:321:14
                io_rm_wid_1,	// ventus/src/pipeline/CSR.scala:321:14
                io_rm_wid_2,	// ventus/src/pipeline/CSR.scala:321:14
  output [2:0]  io_rm_0,	// ventus/src/pipeline/CSR.scala:321:14
                io_rm_1,	// ventus/src/pipeline/CSR.scala:321:14
                io_rm_2,	// ventus/src/pipeline/CSR.scala:321:14
  input         io_CTA2csr_valid,	// ventus/src/pipeline/CSR.scala:321:14
  input  [2:0]  io_CTA2csr_bits_CTAdata_dispatch2cu_wg_wf_count,	// ventus/src/pipeline/CSR.scala:321:14
  input  [3:0]  io_CTA2csr_bits_CTAdata_dispatch2cu_wf_size_dispatch,	// ventus/src/pipeline/CSR.scala:321:14
  input  [10:0] io_CTA2csr_bits_CTAdata_dispatch2cu_sgpr_base_dispatch,	// ventus/src/pipeline/CSR.scala:321:14
                io_CTA2csr_bits_CTAdata_dispatch2cu_vgpr_base_dispatch,	// ventus/src/pipeline/CSR.scala:321:14
  input  [17:0] io_CTA2csr_bits_CTAdata_dispatch2cu_lds_base_dispatch,	// ventus/src/pipeline/CSR.scala:321:14
  input  [4:0]  io_CTA2csr_bits_CTAdata_dispatch2cu_wf_tag_dispatch,	// ventus/src/pipeline/CSR.scala:321:14
  input  [31:0] io_CTA2csr_bits_CTAdata_dispatch2cu_pds_base_dispatch,	// ventus/src/pipeline/CSR.scala:321:14
                io_CTA2csr_bits_CTAdata_dispatch2cu_csr_knl_dispatch,	// ventus/src/pipeline/CSR.scala:321:14
  input  [10:0] io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_x_dispatch,	// ventus/src/pipeline/CSR.scala:321:14
                io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_y_dispatch,	// ventus/src/pipeline/CSR.scala:321:14
                io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_z_dispatch,	// ventus/src/pipeline/CSR.scala:321:14
  input  [31:0] io_CTA2csr_bits_CTAdata_dispatch2cu_wg_id,	// ventus/src/pipeline/CSR.scala:321:14
  input  [1:0]  io_CTA2csr_bits_wid,	// ventus/src/pipeline/CSR.scala:321:14
  output [10:0] io_sgpr_base_0,	// ventus/src/pipeline/CSR.scala:321:14
                io_sgpr_base_1,	// ventus/src/pipeline/CSR.scala:321:14
                io_sgpr_base_2,	// ventus/src/pipeline/CSR.scala:321:14
                io_sgpr_base_3,	// ventus/src/pipeline/CSR.scala:321:14
                io_vgpr_base_0,	// ventus/src/pipeline/CSR.scala:321:14
                io_vgpr_base_1,	// ventus/src/pipeline/CSR.scala:321:14
                io_vgpr_base_2,	// ventus/src/pipeline/CSR.scala:321:14
                io_vgpr_base_3,	// ventus/src/pipeline/CSR.scala:321:14
  input  [1:0]  io_lsu_wid,	// ventus/src/pipeline/CSR.scala:321:14
                io_simt_wid,	// ventus/src/pipeline/CSR.scala:321:14
  output [31:0] io_lsu_tid,	// ventus/src/pipeline/CSR.scala:321:14
                io_lsu_pds,	// ventus/src/pipeline/CSR.scala:321:14
                io_lsu_numw,	// ventus/src/pipeline/CSR.scala:321:14
                io_simt_rpc	// ventus/src/pipeline/CSR.scala:321:14
);

  wire             io_in_ready_0;	// ventus/src/pipeline/CSR.scala:359:36
  wire             _result_io_enq_ready;	// ventus/src/pipeline/CSR.scala:356:20
  wire [31:0]      _CSRFile_3_io_wb_wxd_rd;	// ventus/src/pipeline/CSR.scala:337:45
  wire [2:0]       _CSRFile_3_io_frm;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_3_io_simt_rpc;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_3_io_lsu_tid;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_3_io_lsu_pds;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_3_io_lsu_numw;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_2_io_wb_wxd_rd;	// ventus/src/pipeline/CSR.scala:337:45
  wire [2:0]       _CSRFile_2_io_frm;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_2_io_simt_rpc;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_2_io_lsu_tid;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_2_io_lsu_pds;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_2_io_lsu_numw;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_1_io_wb_wxd_rd;	// ventus/src/pipeline/CSR.scala:337:45
  wire [2:0]       _CSRFile_1_io_frm;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_1_io_simt_rpc;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_1_io_lsu_tid;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_1_io_lsu_pds;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_1_io_lsu_numw;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_io_wb_wxd_rd;	// ventus/src/pipeline/CSR.scala:337:45
  wire [2:0]       _CSRFile_io_frm;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_io_simt_rpc;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_io_lsu_tid;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_io_lsu_pds;	// ventus/src/pipeline/CSR.scala:337:45
  wire [31:0]      _CSRFile_io_lsu_numw;	// ventus/src/pipeline/CSR.scala:337:45
  wire [3:0][31:0] _GEN =
    {{_CSRFile_3_io_lsu_tid},
     {_CSRFile_2_io_lsu_tid},
     {_CSRFile_1_io_lsu_tid},
     {_CSRFile_io_lsu_tid}};	// ventus/src/pipeline/CSR.scala:337:45, :349:13
  wire [3:0][31:0] _GEN_0 =
    {{_CSRFile_3_io_lsu_pds},
     {_CSRFile_2_io_lsu_pds},
     {_CSRFile_1_io_lsu_pds},
     {_CSRFile_io_lsu_pds}};	// ventus/src/pipeline/CSR.scala:337:45, :349:13
  wire [3:0][31:0] _GEN_1 =
    {{_CSRFile_3_io_lsu_numw},
     {_CSRFile_2_io_lsu_numw},
     {_CSRFile_1_io_lsu_numw},
     {_CSRFile_io_lsu_numw}};	// ventus/src/pipeline/CSR.scala:337:45, :349:13
  wire [3:0][31:0] _GEN_2 =
    {{_CSRFile_3_io_simt_rpc},
     {_CSRFile_2_io_simt_rpc},
     {_CSRFile_1_io_simt_rpc},
     {_CSRFile_io_simt_rpc}};	// ventus/src/pipeline/CSR.scala:337:45, :352:14
  wire             _result_io_enq_valid_T = io_in_ready_0 & io_in_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/pipeline/CSR.scala:359:36
  wire [3:0][31:0] _GEN_3 =
    {{_CSRFile_3_io_wb_wxd_rd},
     {_CSRFile_2_io_wb_wxd_rd},
     {_CSRFile_1_io_wb_wxd_rd},
     {_CSRFile_io_wb_wxd_rd}};	// ventus/src/pipeline/CSR.scala:337:45, :354:34
  assign io_in_ready_0 = _result_io_enq_ready & ~io_CTA2csr_valid;	// ventus/src/pipeline/CSR.scala:356:20, :359:{36,38}
  wire [3:0][2:0]  _GEN_4 =
    {{_CSRFile_3_io_frm}, {_CSRFile_2_io_frm}, {_CSRFile_1_io_frm}, {_CSRFile_io_frm}};	// ventus/src/pipeline/CSR.scala:337:45, :369:13
  CSRFile CSRFile (	// ventus/src/pipeline/CSR.scala:337:45
    .clock                                                  (clock),
    .reset                                                  (reset),
    .io_ctrl_inst                                           (io_in_bits_ctrl_inst),
    .io_ctrl_csr                                            (io_in_bits_ctrl_csr),
    .io_ctrl_isvec                                          (io_in_bits_ctrl_isvec),
    .io_ctrl_custom_signal_0
      (io_in_bits_ctrl_custom_signal_0),
    .io_in1                                                 (io_in_bits_in1),
    .io_write
      (io_in_bits_ctrl_wid == 2'h0 & _result_io_enq_valid_T),	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/pipeline/CSR.scala:340:12, :354:34
    .io_wb_wxd_rd                                           (_CSRFile_io_wb_wxd_rd),
    .io_frm                                                 (_CSRFile_io_frm),
    .io_CTA2csr_valid
      (io_CTA2csr_bits_wid == 2'h0 & io_CTA2csr_valid),	// ventus/src/pipeline/CSR.scala:342:20, :354:34, :355:42
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wg_wf_count
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wg_wf_count),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wf_size_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wf_size_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_sgpr_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_sgpr_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_vgpr_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_vgpr_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_lds_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_lds_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wf_tag_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wf_tag_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_pds_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_pds_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_csr_knl_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_csr_knl_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_x_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_x_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_y_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_y_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_z_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_z_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wg_id
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wg_id),
    .io_sgpr_base                                           (io_sgpr_base_0),
    .io_vgpr_base                                           (io_vgpr_base_0),
    .io_simt_rpc                                            (_CSRFile_io_simt_rpc),
    .io_lsu_tid                                             (_CSRFile_io_lsu_tid),
    .io_lsu_pds                                             (_CSRFile_io_lsu_pds),
    .io_lsu_numw                                            (_CSRFile_io_lsu_numw)
  );
  CSRFile CSRFile_1 (	// ventus/src/pipeline/CSR.scala:337:45
    .clock                                                  (clock),
    .reset                                                  (reset),
    .io_ctrl_inst                                           (io_in_bits_ctrl_inst),
    .io_ctrl_csr                                            (io_in_bits_ctrl_csr),
    .io_ctrl_isvec                                          (io_in_bits_ctrl_isvec),
    .io_ctrl_custom_signal_0
      (io_in_bits_ctrl_custom_signal_0),
    .io_in1                                                 (io_in_bits_in1),
    .io_write
      (io_in_bits_ctrl_wid == 2'h1 & _result_io_enq_valid_T),	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/pipeline/CSR.scala:340:12, :354:34
    .io_wb_wxd_rd                                           (_CSRFile_1_io_wb_wxd_rd),
    .io_frm                                                 (_CSRFile_1_io_frm),
    .io_CTA2csr_valid
      (io_CTA2csr_bits_wid == 2'h1 & io_CTA2csr_valid),	// ventus/src/pipeline/CSR.scala:342:20, :354:34, :355:42
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wg_wf_count
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wg_wf_count),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wf_size_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wf_size_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_sgpr_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_sgpr_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_vgpr_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_vgpr_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_lds_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_lds_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wf_tag_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wf_tag_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_pds_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_pds_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_csr_knl_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_csr_knl_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_x_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_x_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_y_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_y_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_z_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_z_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wg_id
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wg_id),
    .io_sgpr_base                                           (io_sgpr_base_1),
    .io_vgpr_base                                           (io_vgpr_base_1),
    .io_simt_rpc                                            (_CSRFile_1_io_simt_rpc),
    .io_lsu_tid                                             (_CSRFile_1_io_lsu_tid),
    .io_lsu_pds                                             (_CSRFile_1_io_lsu_pds),
    .io_lsu_numw                                            (_CSRFile_1_io_lsu_numw)
  );
  CSRFile CSRFile_2 (	// ventus/src/pipeline/CSR.scala:337:45
    .clock                                                  (clock),
    .reset                                                  (reset),
    .io_ctrl_inst                                           (io_in_bits_ctrl_inst),
    .io_ctrl_csr                                            (io_in_bits_ctrl_csr),
    .io_ctrl_isvec                                          (io_in_bits_ctrl_isvec),
    .io_ctrl_custom_signal_0
      (io_in_bits_ctrl_custom_signal_0),
    .io_in1                                                 (io_in_bits_in1),
    .io_write
      (io_in_bits_ctrl_wid == 2'h2 & _result_io_enq_valid_T),	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/pipeline/CSR.scala:340:12, :354:34
    .io_wb_wxd_rd                                           (_CSRFile_2_io_wb_wxd_rd),
    .io_frm                                                 (_CSRFile_2_io_frm),
    .io_CTA2csr_valid
      (io_CTA2csr_bits_wid == 2'h2 & io_CTA2csr_valid),	// ventus/src/pipeline/CSR.scala:342:20, :354:34, :355:42
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wg_wf_count
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wg_wf_count),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wf_size_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wf_size_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_sgpr_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_sgpr_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_vgpr_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_vgpr_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_lds_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_lds_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wf_tag_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wf_tag_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_pds_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_pds_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_csr_knl_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_csr_knl_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_x_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_x_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_y_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_y_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_z_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_z_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wg_id
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wg_id),
    .io_sgpr_base                                           (io_sgpr_base_2),
    .io_vgpr_base                                           (io_vgpr_base_2),
    .io_simt_rpc                                            (_CSRFile_2_io_simt_rpc),
    .io_lsu_tid                                             (_CSRFile_2_io_lsu_tid),
    .io_lsu_pds                                             (_CSRFile_2_io_lsu_pds),
    .io_lsu_numw                                            (_CSRFile_2_io_lsu_numw)
  );
  CSRFile CSRFile_3 (	// ventus/src/pipeline/CSR.scala:337:45
    .clock                                                  (clock),
    .reset                                                  (reset),
    .io_ctrl_inst                                           (io_in_bits_ctrl_inst),
    .io_ctrl_csr                                            (io_in_bits_ctrl_csr),
    .io_ctrl_isvec                                          (io_in_bits_ctrl_isvec),
    .io_ctrl_custom_signal_0
      (io_in_bits_ctrl_custom_signal_0),
    .io_in1                                                 (io_in_bits_in1),
    .io_write
      ((&io_in_bits_ctrl_wid) & _result_io_enq_valid_T),	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/pipeline/CSR.scala:340:12, :354:34
    .io_wb_wxd_rd                                           (_CSRFile_3_io_wb_wxd_rd),
    .io_frm                                                 (_CSRFile_3_io_frm),
    .io_CTA2csr_valid
      ((&io_CTA2csr_bits_wid) & io_CTA2csr_valid),	// ventus/src/pipeline/CSR.scala:342:20, :355:42
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wg_wf_count
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wg_wf_count),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wf_size_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wf_size_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_sgpr_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_sgpr_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_vgpr_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_vgpr_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_lds_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_lds_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wf_tag_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wf_tag_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_pds_base_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_pds_base_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_csr_knl_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_csr_knl_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_x_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_x_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_y_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_y_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_z_dispatch
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wgid_z_dispatch),
    .io_CTA2csr_bits_CTAdata_dispatch2cu_wg_id
      (io_CTA2csr_bits_CTAdata_dispatch2cu_wg_id),
    .io_sgpr_base                                           (io_sgpr_base_3),
    .io_vgpr_base                                           (io_vgpr_base_3),
    .io_simt_rpc                                            (_CSRFile_3_io_simt_rpc),
    .io_lsu_tid                                             (_CSRFile_3_io_lsu_tid),
    .io_lsu_pds                                             (_CSRFile_3_io_lsu_pds),
    .io_lsu_numw                                            (_CSRFile_3_io_lsu_numw)
  );
  Queue1_WriteScalarCtrl result (	// ventus/src/pipeline/CSR.scala:356:20
    .clock                        (clock),
    .reset                        (reset),
    .io_enq_ready                 (_result_io_enq_ready),
    .io_enq_valid                 (_result_io_enq_valid_T),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .io_enq_bits_wb_wxd_rd        (_GEN_3[io_in_bits_ctrl_wid]),	// ventus/src/pipeline/CSR.scala:354:34
    .io_enq_bits_wxd              (io_in_bits_ctrl_wxd),
    .io_enq_bits_reg_idxw         (io_in_bits_ctrl_reg_idxw),
    .io_enq_bits_warp_id          (io_in_bits_ctrl_wid),
    .io_enq_bits_spike_info_sm_id (io_in_bits_ctrl_spike_info_sm_id),
    .io_enq_bits_spike_info_pc    (io_in_bits_ctrl_spike_info_pc),
    .io_enq_bits_spike_info_inst  (io_in_bits_ctrl_spike_info_inst),
    .io_deq_ready                 (io_out_ready),
    .io_deq_valid                 (io_out_valid),
    .io_deq_bits_wb_wxd_rd        (io_out_bits_wb_wxd_rd),
    .io_deq_bits_wxd              (io_out_bits_wxd),
    .io_deq_bits_reg_idxw         (io_out_bits_reg_idxw),
    .io_deq_bits_warp_id          (io_out_bits_warp_id),
    .io_deq_bits_spike_info_sm_id (io_out_bits_spike_info_sm_id),
    .io_deq_bits_spike_info_pc    (io_out_bits_spike_info_pc),
    .io_deq_bits_spike_info_inst  (io_out_bits_spike_info_inst)
  );
  assign io_in_ready = io_in_ready_0;	// ventus/src/pipeline/CSR.scala:320:7, :359:36
  assign io_rm_0 = _GEN_4[io_rm_wid_0];	// ventus/src/pipeline/CSR.scala:320:7, :369:13
  assign io_rm_1 = _GEN_4[io_rm_wid_1];	// ventus/src/pipeline/CSR.scala:320:7, :369:13
  assign io_rm_2 = _GEN_4[io_rm_wid_2];	// ventus/src/pipeline/CSR.scala:320:7, :369:13
  assign io_lsu_tid = _GEN[io_lsu_wid];	// ventus/src/pipeline/CSR.scala:320:7, :349:13
  assign io_lsu_pds = _GEN_0[io_lsu_wid];	// ventus/src/pipeline/CSR.scala:320:7, :349:13
  assign io_lsu_numw = _GEN_1[io_lsu_wid];	// ventus/src/pipeline/CSR.scala:320:7, :349:13
  assign io_simt_rpc = _GEN_2[io_simt_wid];	// ventus/src/pipeline/CSR.scala:320:7, :352:14
endmodule

