// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module SourceD(	// ventus/src/L2cache/SourceD.scala:42:7
  input           clock,	// ventus/src/L2cache/SourceD.scala:42:7
                  reset,	// ventus/src/L2cache/SourceD.scala:42:7
  output          io_req_ready,	// ventus/src/L2cache/SourceD.scala:44:14
  input           io_req_valid,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [2:0]    io_req_bits_opcode,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [6:0]    io_req_bits_size,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [14:0]   io_req_bits_source,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [18:0]   io_req_bits_tag,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [6:0]    io_req_bits_offset,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [4:0]    io_req_bits_put,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [1023:0] io_req_bits_data,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [127:0]  io_req_bits_mask,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [2:0]    io_req_bits_param,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [5:0]    io_req_bits_set,	// ventus/src/L2cache/SourceD.scala:44:14
  input           io_req_bits_hit,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [3:0]    io_req_bits_way,	// ventus/src/L2cache/SourceD.scala:44:14
  input           io_req_bits_dirty,	// ventus/src/L2cache/SourceD.scala:44:14
                  io_req_bits_last_flush,	// ventus/src/L2cache/SourceD.scala:44:14
                  io_req_bits_from_mem,	// ventus/src/L2cache/SourceD.scala:44:14
                  io_d_ready,	// ventus/src/L2cache/SourceD.scala:44:14
  output          io_d_valid,	// ventus/src/L2cache/SourceD.scala:44:14
  output [2:0]    io_d_bits_opcode,	// ventus/src/L2cache/SourceD.scala:44:14
  output [14:0]   io_d_bits_source,	// ventus/src/L2cache/SourceD.scala:44:14
  output [1023:0] io_d_bits_data,	// ventus/src/L2cache/SourceD.scala:44:14
  output [31:0]   io_d_bits_address,	// ventus/src/L2cache/SourceD.scala:44:14
  output          io_pb_pop_valid,	// ventus/src/L2cache/SourceD.scala:44:14
  output [4:0]    io_pb_pop_bits_index,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [1023:0] io_pb_beat_data,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [127:0]  io_pb_beat_mask,	// ventus/src/L2cache/SourceD.scala:44:14
  output          io_bs_radr_valid,	// ventus/src/L2cache/SourceD.scala:44:14
  output [3:0]    io_bs_radr_bits_way,	// ventus/src/L2cache/SourceD.scala:44:14
  output [5:0]    io_bs_radr_bits_set,	// ventus/src/L2cache/SourceD.scala:44:14
  input  [1023:0] io_bs_rdat_data,	// ventus/src/L2cache/SourceD.scala:44:14
  input           io_bs_wadr_ready,	// ventus/src/L2cache/SourceD.scala:44:14
  output          io_bs_wadr_valid,	// ventus/src/L2cache/SourceD.scala:44:14
  output [3:0]    io_bs_wadr_bits_way,	// ventus/src/L2cache/SourceD.scala:44:14
  output [5:0]    io_bs_wadr_bits_set,	// ventus/src/L2cache/SourceD.scala:44:14
  output [127:0]  io_bs_wadr_bits_mask,	// ventus/src/L2cache/SourceD.scala:44:14
  output [1023:0] io_bs_wdat_data,	// ventus/src/L2cache/SourceD.scala:44:14
  input           io_a_ready,	// ventus/src/L2cache/SourceD.scala:44:14
  output          io_a_valid,	// ventus/src/L2cache/SourceD.scala:44:14
  output [6:0]    io_a_bits_size,	// ventus/src/L2cache/SourceD.scala:44:14
  output [14:0]   io_a_bits_source,	// ventus/src/L2cache/SourceD.scala:44:14
  output [18:0]   io_a_bits_tag,	// ventus/src/L2cache/SourceD.scala:44:14
  output [6:0]    io_a_bits_offset,	// ventus/src/L2cache/SourceD.scala:44:14
  output [4:0]    io_a_bits_put,	// ventus/src/L2cache/SourceD.scala:44:14
  output [1023:0] io_a_bits_data,	// ventus/src/L2cache/SourceD.scala:44:14
  output [127:0]  io_a_bits_mask,	// ventus/src/L2cache/SourceD.scala:44:14
  output [2:0]    io_a_bits_param,	// ventus/src/L2cache/SourceD.scala:44:14
  output [5:0]    io_a_bits_set,	// ventus/src/L2cache/SourceD.scala:44:14
  output          io_mshr_wait,	// ventus/src/L2cache/SourceD.scala:44:14
                  io_finish_issue	// ventus/src/L2cache/SourceD.scala:44:14
);

  reg           busy;	// ventus/src/L2cache/SourceD.scala:78:21
  wire          _write_sent_T = ~busy & io_req_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:78:21, :105:20
  reg  [1023:0] pb_beat_reg_data;	// ventus/src/L2cache/SourceD.scala:66:26
  reg  [127:0]  pb_beat_reg_mask;	// ventus/src/L2cache/SourceD.scala:66:26
  reg  [2:0]    stateReg;	// ventus/src/L2cache/SourceD.scala:69:24
  reg  [2:0]    s1_req_reg_opcode;	// ventus/src/L2cache/SourceD.scala:73:27
  reg  [6:0]    s1_req_reg_size;	// ventus/src/L2cache/SourceD.scala:73:27
  reg  [14:0]   s1_req_reg_source;	// ventus/src/L2cache/SourceD.scala:73:27
  reg  [18:0]   s1_req_reg_tag;	// ventus/src/L2cache/SourceD.scala:73:27
  reg  [6:0]    s1_req_reg_offset;	// ventus/src/L2cache/SourceD.scala:73:27
  reg  [4:0]    s1_req_reg_put;	// ventus/src/L2cache/SourceD.scala:73:27
  reg  [1023:0] s1_req_reg_data;	// ventus/src/L2cache/SourceD.scala:73:27
  reg  [127:0]  s1_req_reg_mask;	// ventus/src/L2cache/SourceD.scala:73:27
  reg  [2:0]    s1_req_reg_param;	// ventus/src/L2cache/SourceD.scala:73:27
  reg  [5:0]    s1_req_reg_set;	// ventus/src/L2cache/SourceD.scala:73:27
  reg           s1_req_reg_hit;	// ventus/src/L2cache/SourceD.scala:73:27
  reg  [3:0]    s1_req_reg_way;	// ventus/src/L2cache/SourceD.scala:73:27
  reg           s1_req_reg_dirty;	// ventus/src/L2cache/SourceD.scala:73:27
  reg           s1_req_reg_last_flush;	// ventus/src/L2cache/SourceD.scala:73:27
  reg           s1_req_reg_from_mem;	// ventus/src/L2cache/SourceD.scala:73:27
  wire [2:0]    s1_req_opcode = _write_sent_T ? io_req_bits_opcode : s1_req_reg_opcode;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18
  wire [5:0]    s1_req_set = _write_sent_T ? io_req_bits_set : s1_req_reg_set;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18
  wire          s1_req_hit = _write_sent_T ? io_req_bits_hit : s1_req_reg_hit;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18
  wire [3:0]    s1_req_way = _write_sent_T ? io_req_bits_way : s1_req_reg_way;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18
  wire          s1_req_dirty = _write_sent_T ? io_req_bits_dirty : s1_req_reg_dirty;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18
  wire          s1_req_from_mem =
    _write_sent_T ? io_req_bits_from_mem : s1_req_reg_from_mem;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18
  reg  [2:0]    s_final_req_opcode;	// ventus/src/L2cache/SourceD.scala:82:26
  reg  [6:0]    s_final_req_size;	// ventus/src/L2cache/SourceD.scala:82:26
  reg  [14:0]   s_final_req_source;	// ventus/src/L2cache/SourceD.scala:82:26
  reg  [18:0]   s_final_req_tag;	// ventus/src/L2cache/SourceD.scala:82:26
  reg  [6:0]    s_final_req_offset;	// ventus/src/L2cache/SourceD.scala:82:26
  reg  [4:0]    s_final_req_put;	// ventus/src/L2cache/SourceD.scala:82:26
  reg  [1023:0] s_final_req_data;	// ventus/src/L2cache/SourceD.scala:82:26
  reg  [127:0]  s_final_req_mask;	// ventus/src/L2cache/SourceD.scala:82:26
  reg  [2:0]    s_final_req_param;	// ventus/src/L2cache/SourceD.scala:82:26
  reg  [5:0]    s_final_req_set;	// ventus/src/L2cache/SourceD.scala:82:26
  reg           s_final_req_hit;	// ventus/src/L2cache/SourceD.scala:82:26
  reg           s_final_req_dirty;	// ventus/src/L2cache/SourceD.scala:82:26
  reg           s_final_req_last_flush;	// ventus/src/L2cache/SourceD.scala:82:26
  wire          _s1_need_w_T = s1_req_opcode == 3'h0;	// ventus/src/L2cache/SourceD.scala:69:24, :81:18, :83:32
  wire          _s1_need_w_T_1 = s1_req_opcode == 3'h1;	// ventus/src/L2cache/SourceD.scala:81:18, :83:63, :169:22
  wire          s1_need_w =
    (_s1_need_w_T | _s1_need_w_T_1) & ~s1_req_from_mem & s1_req_hit;	// ventus/src/L2cache/SourceD.scala:81:18, :83:{32,47,63,85,102}
  wire          _s1_need_r_T_3 = s1_req_opcode == 3'h5;	// ventus/src/L2cache/SourceD.scala:71:25, :81:18, :85:88
  wire          s1_need_r =
    s1_req_opcode == 3'h4 & s1_req_hit | (~s1_req_hit | _s1_need_r_T_3) & s1_req_dirty;	// ventus/src/L2cache/SourceD.scala:81:18, :85:{33,41,56,61,73,88,97}
  reg           read_sent_reg;	// ventus/src/L2cache/SourceD.scala:91:28
  wire          _io_a_valid_T = stateReg == 3'h3;	// ventus/src/L2cache/SourceD.scala:69:24, :103:79
  wire          _io_a_bits_data_T = s_final_req_opcode == 3'h0;	// ventus/src/L2cache/SourceD.scala:69:24, :82:26, :103:140
  wire          _io_a_bits_data_T_1 = s_final_req_opcode == 3'h1;	// ventus/src/L2cache/SourceD.scala:82:26, :103:178, :169:22
  reg           write_sent_reg;	// ventus/src/L2cache/SourceD.scala:117:29
  reg           tobedone;	// ventus/src/L2cache/SourceD.scala:127:21
  reg           mshr_wait_reg;	// ventus/src/L2cache/SourceD.scala:128:27
  wire          _io_a_valid_T_6 = s_final_req_opcode == 3'h5;	// ventus/src/L2cache/SourceD.scala:71:25, :82:26, :264:89
  wire          io_d_valid_0 =
    (_io_a_valid_T | (&stateReg)) & ~(_io_a_valid_T_6 & ~s_final_req_last_flush);	// ventus/src/L2cache/SourceD.scala:69:24, :82:26, :103:{79,250}, :264:{44,66,69,89,97,100}
  wire          _io_d_bits_data_T = s_final_req_opcode == 3'h4;	// ventus/src/L2cache/SourceD.scala:82:26, :85:33, :266:45
  wire          io_a_valid_0 =
    (_io_a_valid_T | stateReg == 3'h6 | stateReg == 3'h2)
    & (~s_final_req_hit | _io_a_valid_T_6)
    & (s_final_req_dirty | _io_a_bits_data_T | _io_a_bits_data_T_1);	// ventus/src/L2cache/SourceD.scala:69:24, :82:26, :103:{38,79,100,140,178}, :104:16, :264:89, :274:{63,86,108,195}
  always @(posedge clock) begin	// ventus/src/L2cache/SourceD.scala:42:7
    automatic logic s1_req_last_flush;	// ventus/src/L2cache/SourceD.scala:81:18
    s1_req_last_flush = _write_sent_T ? io_req_bits_last_flush : s1_req_reg_last_flush;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18
    if (reset) begin	// ventus/src/L2cache/SourceD.scala:42:7
      pb_beat_reg_data <= 1024'h0;	// ventus/src/L2cache/SourceD.scala:65:45, :66:26
      pb_beat_reg_mask <= 128'h0;	// ventus/src/L2cache/SourceD.scala:65:45, :66:26
      stateReg <= 3'h0;	// ventus/src/L2cache/SourceD.scala:69:24
      s1_req_reg_opcode <= 3'h5;	// ventus/src/L2cache/SourceD.scala:71:25, :73:27
      s1_req_reg_size <= 7'h0;	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
      s1_req_reg_source <= 15'h0;	// ventus/src/L2cache/SourceD.scala:70:44, :73:27
      s1_req_reg_tag <= 19'h0;	// ventus/src/L2cache/SourceD.scala:70:44, :73:27
      s1_req_reg_offset <= 7'h0;	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
      s1_req_reg_put <= 5'h0;	// ventus/src/L2cache/SourceD.scala:70:44, :73:27
      s1_req_reg_data <= 1024'h0;	// ventus/src/L2cache/SourceD.scala:65:45, :73:27
      s1_req_reg_mask <= 128'h0;	// ventus/src/L2cache/SourceD.scala:65:45, :73:27
      s1_req_reg_param <= 3'h0;	// ventus/src/L2cache/SourceD.scala:69:24, :73:27
      s1_req_reg_set <= 6'h0;	// ventus/src/L2cache/SourceD.scala:70:44, :73:27
      s1_req_reg_hit <= 1'h0;	// ventus/src/L2cache/SourceD.scala:63:55, :73:27
      s1_req_reg_way <= 4'h0;	// ventus/src/L2cache/SourceD.scala:70:44, :73:27
      s1_req_reg_dirty <= 1'h0;	// ventus/src/L2cache/SourceD.scala:63:55, :73:27
      s1_req_reg_last_flush <= 1'h0;	// ventus/src/L2cache/SourceD.scala:63:55, :73:27
      s1_req_reg_from_mem <= 1'h0;	// ventus/src/L2cache/SourceD.scala:63:55, :73:27
      busy <= 1'h0;	// ventus/src/L2cache/SourceD.scala:63:55, :78:21
      read_sent_reg <= 1'h0;	// ventus/src/L2cache/SourceD.scala:63:55, :91:28
      write_sent_reg <= 1'h0;	// ventus/src/L2cache/SourceD.scala:63:55, :117:29
      tobedone <= 1'h0;	// ventus/src/L2cache/SourceD.scala:63:55, :127:21
      mshr_wait_reg <= 1'h0;	// ventus/src/L2cache/SourceD.scala:63:55, :128:27
    end
    else begin	// ventus/src/L2cache/SourceD.scala:42:7
      automatic logic       _about_to_not_busy_T_21;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      automatic logic       _about_to_not_busy_T_17;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      automatic logic       _GEN;	// ventus/src/L2cache/SourceD.scala:133:25
      automatic logic       _GEN_0;	// ventus/src/L2cache/SourceD.scala:163:108
      automatic logic       _GEN_1;	// ventus/src/L2cache/SourceD.scala:192:41
      automatic logic       _GEN_2;	// ventus/src/L2cache/SourceD.scala:135:27, :152:46, :163:123, :192:62
      automatic logic       _GEN_3;	// ventus/src/L2cache/SourceD.scala:78:21, :210:23, :212:14
      automatic logic       _GEN_4;	// ventus/src/L2cache/SourceD.scala:127:21, :210:23, :213:18
      automatic logic       _GEN_5;	// ventus/src/L2cache/SourceD.scala:128:27, :210:23, :214:23
      automatic logic       _GEN_6;	// ventus/src/L2cache/SourceD.scala:218:107
      automatic logic       _GEN_7;	// ventus/src/L2cache/SourceD.scala:219:24
      automatic logic       _GEN_8;	// ventus/src/L2cache/SourceD.scala:69:24, :129:19, :248:22, :249:18
      automatic logic       _GEN_9;	// ventus/src/L2cache/SourceD.scala:78:21, :129:19, :248:22, :250:14
      automatic logic       _GEN_10;	// ventus/src/L2cache/SourceD.scala:127:21, :129:19, :248:22, :251:18
      automatic logic       _GEN_11;	// ventus/src/L2cache/SourceD.scala:128:27, :129:19, :248:22, :252:23
      automatic logic [7:0] _GEN_12;	// ventus/src/L2cache/SourceD.scala:78:21, :129:19, :133:38, :210:23, :218:137, :240:22
      automatic logic [7:0] _GEN_13;	// ventus/src/L2cache/SourceD.scala:127:21, :129:19, :133:38, :210:23, :218:137, :240:22
      automatic logic [7:0] _GEN_14;	// ventus/src/L2cache/SourceD.scala:128:27, :129:19, :133:38, :210:23, :218:137, :240:22
      _about_to_not_busy_T_21 = io_a_ready & io_a_valid_0;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:274:86
      _about_to_not_busy_T_17 = io_d_ready & io_d_valid_0;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:264:66
      _GEN = _write_sent_T | tobedone;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:127:21, :133:25
      _GEN_0 = (_s1_need_w_T | _s1_need_w_T_1) & ~s1_req_from_mem & s1_req_hit;	// ventus/src/L2cache/SourceD.scala:81:18, :83:{32,63,85}, :163:{51,108}
      _GEN_1 = _s1_need_r_T_3 & s1_req_last_flush;	// ventus/src/L2cache/SourceD.scala:81:18, :85:88, :192:41
      _GEN_2 = s1_need_r | _GEN_0;	// ventus/src/L2cache/SourceD.scala:85:56, :135:27, :152:46, :163:{108,123}, :192:62
      _GEN_3 = ~_about_to_not_busy_T_21 & busy;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:78:21, :210:23, :212:14
      _GEN_4 = ~_about_to_not_busy_T_21 & tobedone;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:78:21, :127:21, :210:23, :212:14, :213:18
      _GEN_5 = ~_about_to_not_busy_T_21 & mshr_wait_reg;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:78:21, :128:27, :210:23, :212:14, :214:23
      _GEN_6 =
        ~s_final_req_hit & (_io_a_bits_data_T | _io_a_bits_data_T_1)
        | s_final_req_opcode == 3'h5;	// ventus/src/L2cache/SourceD.scala:71:25, :82:26, :103:{100,140,178}, :218:{30,67,107,128}
      _GEN_7 = _about_to_not_busy_T_17 & _about_to_not_busy_T_21;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:219:24
      _GEN_8 = (&stateReg) & _about_to_not_busy_T_17;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:69:24, :129:19, :248:22, :249:18
      _GEN_9 = ~_GEN_8 & busy;	// ventus/src/L2cache/SourceD.scala:69:24, :78:21, :129:19, :248:22, :249:18, :250:14
      _GEN_10 = ~_GEN_8 & tobedone;	// ventus/src/L2cache/SourceD.scala:69:24, :78:21, :127:21, :129:19, :248:22, :249:18, :250:14, :251:18
      _GEN_11 = ~_GEN_8 & mshr_wait_reg;	// ventus/src/L2cache/SourceD.scala:69:24, :78:21, :128:27, :129:19, :248:22, :249:18, :250:14, :252:23
      if (_write_sent_T) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        pb_beat_reg_data <= io_pb_beat_data;	// ventus/src/L2cache/SourceD.scala:66:26
        pb_beat_reg_mask <= io_pb_beat_mask;	// ventus/src/L2cache/SourceD.scala:66:26
        s1_req_reg_opcode <= io_req_bits_opcode;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_size <= io_req_bits_size;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_source <= io_req_bits_source;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_tag <= io_req_bits_tag;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_offset <= io_req_bits_offset;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_put <= io_req_bits_put;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_data <= io_req_bits_data;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_mask <= io_req_bits_mask;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_param <= io_req_bits_param;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_set <= io_req_bits_set;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_hit <= io_req_bits_hit;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_way <= io_req_bits_way;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_dirty <= io_req_bits_dirty;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_last_flush <= io_req_bits_last_flush;	// ventus/src/L2cache/SourceD.scala:73:27
        s1_req_reg_from_mem <= io_req_bits_from_mem;	// ventus/src/L2cache/SourceD.scala:73:27
      end
      if (stateReg == 3'h0) begin	// ventus/src/L2cache/SourceD.scala:69:24, :129:19
        if (_GEN) begin	// ventus/src/L2cache/SourceD.scala:133:25
          if (s1_need_r)	// ventus/src/L2cache/SourceD.scala:85:56
            stateReg <=
              {2'h1,
               ~((~s1_req_hit & s1_req_opcode != 3'h5 | _s1_need_r_T_3
                  & ~s1_req_last_flush) & s1_req_dirty)};	// ventus/src/L2cache/SourceD.scala:69:24, :71:25, :81:18, :85:{61,88}, :153:{30,46,55,82,85,106,123}, :154:22, :159:22, :266:26
          else if (_GEN_0)	// ventus/src/L2cache/SourceD.scala:163:108
            stateReg <= {1'h0, io_bs_wadr_ready, 1'h1};	// ventus/src/L2cache/SourceD.scala:44:14, :63:55, :69:24, :164:34, :165:22, :169:22
          else if (_GEN_1)	// ventus/src/L2cache/SourceD.scala:192:41
            stateReg <= 3'h7;	// ventus/src/L2cache/SourceD.scala:69:24, :103:250
          else if (s1_req_hit | s1_req_dirty) begin	// ventus/src/L2cache/SourceD.scala:69:24, :81:18, :135:27, :136:30
          end
          else	// ventus/src/L2cache/SourceD.scala:69:24, :135:27, :136:30
            stateReg <= 3'h3;	// ventus/src/L2cache/SourceD.scala:69:24, :103:79
        end
      end
      else if (stateReg == 3'h1) begin	// ventus/src/L2cache/SourceD.scala:69:24, :129:19, :169:22
        if (io_bs_wadr_ready)	// ventus/src/L2cache/SourceD.scala:44:14
          stateReg <= 3'h3;	// ventus/src/L2cache/SourceD.scala:69:24, :103:79
      end
      else if (stateReg == 3'h2) begin	// ventus/src/L2cache/SourceD.scala:69:24, :103:38, :129:19
        if (_about_to_not_busy_T_21)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
          stateReg <= 3'h0;	// ventus/src/L2cache/SourceD.scala:69:24
      end
      else if (stateReg == 3'h3) begin	// ventus/src/L2cache/SourceD.scala:69:24, :103:79, :129:19
        if (_GEN_6) begin	// ventus/src/L2cache/SourceD.scala:218:107
          if (_GEN_7)	// ventus/src/L2cache/SourceD.scala:219:24
            stateReg <= 3'h0;	// ventus/src/L2cache/SourceD.scala:69:24
          else if (_about_to_not_busy_T_17)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
            stateReg <= 3'h6;	// ventus/src/L2cache/SourceD.scala:69:24, :104:16
          else if (_about_to_not_busy_T_21)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
            stateReg <= 3'h7;	// ventus/src/L2cache/SourceD.scala:69:24, :103:250
        end
        else if (_about_to_not_busy_T_17)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
          stateReg <= 3'h0;	// ventus/src/L2cache/SourceD.scala:69:24
      end
      else if (stateReg == 3'h6 ? _about_to_not_busy_T_21 : _GEN_8)	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:69:24, :104:16, :129:19, :210:23, :211:18, :240:22, :248:22, :249:18
        stateReg <= 3'h0;	// ventus/src/L2cache/SourceD.scala:69:24
      _GEN_12 =
        {{_GEN_9},
         {_GEN_3},
         {_GEN_9},
         {_GEN_9},
         {_GEN_6 ? ~_GEN_7 & busy : ~_about_to_not_busy_T_17 & busy},
         {_GEN_3},
         {busy},
         {_GEN & (_GEN_2 | ~_GEN_1)}};	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:63:{55,90}, :78:21, :129:19, :131:11, :133:{25,38}, :135:27, :152:46, :153:123, :163:123, :164:34, :192:{41,62}, :194:16, :198:16, :210:23, :212:14, :218:{107,137}, :219:{24,38}, :220:16, :230:25, :232:16, :240:22, :248:22, :250:14
      busy <= _GEN_12[stateReg];	// ventus/src/L2cache/SourceD.scala:69:24, :78:21, :129:19, :133:38, :210:23, :218:137, :240:22
      read_sent_reg <= s1_need_r;	// ventus/src/L2cache/SourceD.scala:85:56, :91:28
      write_sent_reg <= s1_need_w & io_bs_wadr_ready;	// ventus/src/L2cache/SourceD.scala:83:102, :117:29, :118:19
      _GEN_13 =
        {{_GEN_10},
         {_GEN_4},
         {_GEN_10},
         {_GEN_10},
         {_GEN_6 ? ~_GEN_7 & tobedone : ~_about_to_not_busy_T_17 & tobedone},
         {_GEN_4},
         {tobedone},
         {_GEN ? ~_GEN_2 & ~_GEN_1 : tobedone}};	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:63:{55,90}, :78:21, :127:21, :129:19, :133:{25,38}, :135:27, :152:46, :153:123, :163:123, :164:34, :192:{41,62}, :194:16, :198:16, :210:23, :213:18, :218:{107,137}, :219:{24,38}, :220:16, :222:20, :230:25, :232:16, :233:20, :240:22, :248:22, :251:18
      tobedone <= _GEN_13[stateReg];	// ventus/src/L2cache/SourceD.scala:69:24, :127:21, :129:19, :133:38, :210:23, :218:137, :240:22
      _GEN_14 =
        {{_GEN_11},
         {_GEN_5},
         {_GEN_11},
         {_GEN_11},
         {_GEN_6 ? ~_GEN_7 & mshr_wait_reg : ~_about_to_not_busy_T_17 & mshr_wait_reg},
         {_GEN_5},
         {mshr_wait_reg},
         {_GEN & (_GEN_2 | ~_GEN_1) & ~s1_req_hit
            & (s1_req_dirty | _s1_need_w_T & _s1_need_w_T_1)}};	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:78:21, :81:18, :83:{32,63}, :85:61, :128:27, :129:19, :132:21, :133:{25,38}, :135:27, :136:30, :137:27, :142:{48,85}, :152:46, :163:123, :192:{41,62}, :196:25, :210:23, :214:23, :218:{107,137}, :219:{24,38}, :220:16, :223:25, :230:25, :232:16, :234:25, :240:22, :248:22, :252:23
      mshr_wait_reg <= _GEN_14[stateReg];	// ventus/src/L2cache/SourceD.scala:69:24, :128:27, :129:19, :133:38, :210:23, :218:137, :240:22
    end
    s_final_req_opcode <= s1_req_opcode;	// ventus/src/L2cache/SourceD.scala:81:18, :82:26
    s_final_req_size <= _write_sent_T ? io_req_bits_size : s1_req_reg_size;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18, :82:26
    s_final_req_source <= _write_sent_T ? io_req_bits_source : s1_req_reg_source;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18, :82:26
    s_final_req_tag <= _write_sent_T ? io_req_bits_tag : s1_req_reg_tag;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18, :82:26
    s_final_req_offset <= _write_sent_T ? io_req_bits_offset : s1_req_reg_offset;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18, :82:26
    s_final_req_put <= _write_sent_T ? io_req_bits_put : s1_req_reg_put;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18, :82:26
    s_final_req_data <= _write_sent_T ? io_req_bits_data : s1_req_reg_data;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18, :82:26
    s_final_req_mask <= _write_sent_T ? io_req_bits_mask : s1_req_reg_mask;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18, :82:26
    s_final_req_param <= _write_sent_T ? io_req_bits_param : s1_req_reg_param;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:73:27, :81:18, :82:26
    s_final_req_set <= s1_req_set;	// ventus/src/L2cache/SourceD.scala:81:18, :82:26
    s_final_req_hit <= s1_req_hit;	// ventus/src/L2cache/SourceD.scala:81:18, :82:26
    s_final_req_dirty <= s1_req_dirty;	// ventus/src/L2cache/SourceD.scala:81:18, :82:26
    s_final_req_last_flush <= s1_req_last_flush;	// ventus/src/L2cache/SourceD.scala:81:18, :82:26
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// ventus/src/L2cache/SourceD.scala:42:7
    `ifdef FIRRTL_BEFORE_INITIAL	// ventus/src/L2cache/SourceD.scala:42:7
      `FIRRTL_BEFORE_INITIAL	// ventus/src/L2cache/SourceD.scala:42:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// ventus/src/L2cache/SourceD.scala:42:7
      automatic logic [31:0] _RANDOM[0:116];	// ventus/src/L2cache/SourceD.scala:42:7
      `ifdef INIT_RANDOM_PROLOG_	// ventus/src/L2cache/SourceD.scala:42:7
        `INIT_RANDOM_PROLOG_	// ventus/src/L2cache/SourceD.scala:42:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// ventus/src/L2cache/SourceD.scala:42:7
        for (logic [6:0] i = 7'h0; i < 7'h75; i += 7'h1) begin
          _RANDOM[i] = `RANDOM;	// ventus/src/L2cache/SourceD.scala:42:7
        end	// ventus/src/L2cache/SourceD.scala:42:7
        pb_beat_reg_data =
          {_RANDOM[7'h0],
           _RANDOM[7'h1],
           _RANDOM[7'h2],
           _RANDOM[7'h3],
           _RANDOM[7'h4],
           _RANDOM[7'h5],
           _RANDOM[7'h6],
           _RANDOM[7'h7],
           _RANDOM[7'h8],
           _RANDOM[7'h9],
           _RANDOM[7'hA],
           _RANDOM[7'hB],
           _RANDOM[7'hC],
           _RANDOM[7'hD],
           _RANDOM[7'hE],
           _RANDOM[7'hF],
           _RANDOM[7'h10],
           _RANDOM[7'h11],
           _RANDOM[7'h12],
           _RANDOM[7'h13],
           _RANDOM[7'h14],
           _RANDOM[7'h15],
           _RANDOM[7'h16],
           _RANDOM[7'h17],
           _RANDOM[7'h18],
           _RANDOM[7'h19],
           _RANDOM[7'h1A],
           _RANDOM[7'h1B],
           _RANDOM[7'h1C],
           _RANDOM[7'h1D],
           _RANDOM[7'h1E],
           _RANDOM[7'h1F]};	// ventus/src/L2cache/SourceD.scala:42:7, :66:26
        pb_beat_reg_mask =
          {_RANDOM[7'h20], _RANDOM[7'h21], _RANDOM[7'h22], _RANDOM[7'h23]};	// ventus/src/L2cache/SourceD.scala:42:7, :66:26
        stateReg = _RANDOM[7'h24][2:0];	// ventus/src/L2cache/SourceD.scala:42:7, :69:24
        s1_req_reg_opcode = _RANDOM[7'h24][5:3];	// ventus/src/L2cache/SourceD.scala:42:7, :69:24, :73:27
        s1_req_reg_size = _RANDOM[7'h24][12:6];	// ventus/src/L2cache/SourceD.scala:42:7, :69:24, :73:27
        s1_req_reg_source = _RANDOM[7'h24][27:13];	// ventus/src/L2cache/SourceD.scala:42:7, :69:24, :73:27
        s1_req_reg_tag = {_RANDOM[7'h24][31:28], _RANDOM[7'h25][14:0]};	// ventus/src/L2cache/SourceD.scala:42:7, :69:24, :73:27
        s1_req_reg_offset = _RANDOM[7'h25][21:15];	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
        s1_req_reg_put = _RANDOM[7'h25][26:22];	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
        s1_req_reg_data =
          {_RANDOM[7'h25][31:27],
           _RANDOM[7'h26],
           _RANDOM[7'h27],
           _RANDOM[7'h28],
           _RANDOM[7'h29],
           _RANDOM[7'h2A],
           _RANDOM[7'h2B],
           _RANDOM[7'h2C],
           _RANDOM[7'h2D],
           _RANDOM[7'h2E],
           _RANDOM[7'h2F],
           _RANDOM[7'h30],
           _RANDOM[7'h31],
           _RANDOM[7'h32],
           _RANDOM[7'h33],
           _RANDOM[7'h34],
           _RANDOM[7'h35],
           _RANDOM[7'h36],
           _RANDOM[7'h37],
           _RANDOM[7'h38],
           _RANDOM[7'h39],
           _RANDOM[7'h3A],
           _RANDOM[7'h3B],
           _RANDOM[7'h3C],
           _RANDOM[7'h3D],
           _RANDOM[7'h3E],
           _RANDOM[7'h3F],
           _RANDOM[7'h40],
           _RANDOM[7'h41],
           _RANDOM[7'h42],
           _RANDOM[7'h43],
           _RANDOM[7'h44],
           _RANDOM[7'h45][26:0]};	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
        s1_req_reg_mask =
          {_RANDOM[7'h45][31:27],
           _RANDOM[7'h46],
           _RANDOM[7'h47],
           _RANDOM[7'h48],
           _RANDOM[7'h49][26:0]};	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
        s1_req_reg_param = _RANDOM[7'h49][29:27];	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
        s1_req_reg_set = {_RANDOM[7'h4B][31:30], _RANDOM[7'h4C][3:0]};	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
        s1_req_reg_hit = _RANDOM[7'h4C][4];	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
        s1_req_reg_way = _RANDOM[7'h4C][8:5];	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
        s1_req_reg_dirty = _RANDOM[7'h4C][9];	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
        s1_req_reg_last_flush = _RANDOM[7'h4C][11];	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
        s1_req_reg_from_mem = _RANDOM[7'h4C][12];	// ventus/src/L2cache/SourceD.scala:42:7, :73:27
        busy = _RANDOM[7'h4C][13];	// ventus/src/L2cache/SourceD.scala:42:7, :73:27, :78:21
        s_final_req_opcode = _RANDOM[7'h4C][16:14];	// ventus/src/L2cache/SourceD.scala:42:7, :73:27, :82:26
        s_final_req_size = _RANDOM[7'h4C][23:17];	// ventus/src/L2cache/SourceD.scala:42:7, :73:27, :82:26
        s_final_req_source = {_RANDOM[7'h4C][31:24], _RANDOM[7'h4D][6:0]};	// ventus/src/L2cache/SourceD.scala:42:7, :73:27, :82:26
        s_final_req_tag = _RANDOM[7'h4D][25:7];	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
        s_final_req_offset = {_RANDOM[7'h4D][31:26], _RANDOM[7'h4E][0]};	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
        s_final_req_put = _RANDOM[7'h4E][5:1];	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
        s_final_req_data =
          {_RANDOM[7'h4E][31:6],
           _RANDOM[7'h4F],
           _RANDOM[7'h50],
           _RANDOM[7'h51],
           _RANDOM[7'h52],
           _RANDOM[7'h53],
           _RANDOM[7'h54],
           _RANDOM[7'h55],
           _RANDOM[7'h56],
           _RANDOM[7'h57],
           _RANDOM[7'h58],
           _RANDOM[7'h59],
           _RANDOM[7'h5A],
           _RANDOM[7'h5B],
           _RANDOM[7'h5C],
           _RANDOM[7'h5D],
           _RANDOM[7'h5E],
           _RANDOM[7'h5F],
           _RANDOM[7'h60],
           _RANDOM[7'h61],
           _RANDOM[7'h62],
           _RANDOM[7'h63],
           _RANDOM[7'h64],
           _RANDOM[7'h65],
           _RANDOM[7'h66],
           _RANDOM[7'h67],
           _RANDOM[7'h68],
           _RANDOM[7'h69],
           _RANDOM[7'h6A],
           _RANDOM[7'h6B],
           _RANDOM[7'h6C],
           _RANDOM[7'h6D],
           _RANDOM[7'h6E][5:0]};	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
        s_final_req_mask =
          {_RANDOM[7'h6E][31:6],
           _RANDOM[7'h6F],
           _RANDOM[7'h70],
           _RANDOM[7'h71],
           _RANDOM[7'h72][5:0]};	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
        s_final_req_param = _RANDOM[7'h72][8:6];	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
        s_final_req_set = _RANDOM[7'h74][14:9];	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
        s_final_req_hit = _RANDOM[7'h74][15];	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
        s_final_req_dirty = _RANDOM[7'h74][20];	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
        s_final_req_last_flush = _RANDOM[7'h74][22];	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
        read_sent_reg = _RANDOM[7'h74][24];	// ventus/src/L2cache/SourceD.scala:42:7, :82:26, :91:28
        write_sent_reg = _RANDOM[7'h74][26];	// ventus/src/L2cache/SourceD.scala:42:7, :82:26, :117:29
        tobedone = _RANDOM[7'h74][27];	// ventus/src/L2cache/SourceD.scala:42:7, :82:26, :127:21
        mshr_wait_reg = _RANDOM[7'h74][28];	// ventus/src/L2cache/SourceD.scala:42:7, :82:26, :128:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// ventus/src/L2cache/SourceD.scala:42:7
      `FIRRTL_AFTER_INITIAL	// ventus/src/L2cache/SourceD.scala:42:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_req_ready = ~busy;	// ventus/src/L2cache/SourceD.scala:42:7, :78:21, :105:20
  assign io_d_valid = io_d_valid_0;	// ventus/src/L2cache/SourceD.scala:42:7, :264:66
  assign io_d_bits_opcode =
    {1'h0, _io_d_bits_data_T ? 2'h1 : {s_final_req_last_flush, 1'h0}};	// ventus/src/L2cache/SourceD.scala:42:7, :63:55, :82:26, :266:{21,26,45,69}
  assign io_d_bits_source = s_final_req_source;	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
  assign io_d_bits_data =
    _io_d_bits_data_T ? (s_final_req_hit ? io_bs_rdat_data : s_final_req_data) : 1024'h0;	// ventus/src/L2cache/SourceD.scala:42:7, :65:45, :82:26, :266:45, :268:{26,55}
  assign io_d_bits_address = {s_final_req_tag, s_final_req_set, s_final_req_offset};	// ventus/src/L2cache/Parameters.scala:235:13, ventus/src/L2cache/SourceD.scala:42:7, :82:26
  assign io_pb_pop_valid =
    _write_sent_T & (io_req_bits_opcode == 3'h0 | io_req_bits_opcode == 3'h1);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:42:7, :63:{33,55,69,90}, :69:24, :169:22
  assign io_pb_pop_bits_index = io_req_bits_put;	// ventus/src/L2cache/SourceD.scala:42:7
  assign io_bs_radr_valid = s1_need_r & ~(~_write_sent_T & read_sent_reg);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:42:7, :85:56, :91:28, :97:20, :98:{37,40}
  assign io_bs_radr_bits_way = s1_req_way;	// ventus/src/L2cache/SourceD.scala:42:7, :81:18
  assign io_bs_radr_bits_set = s1_req_set;	// ventus/src/L2cache/SourceD.scala:42:7, :81:18
  assign io_bs_wadr_valid = s1_need_w & ~(~_write_sent_T & write_sent_reg);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:42:7, :83:102, :97:20, :117:29, :123:21, :257:{39,42}
  assign io_bs_wadr_bits_way = s1_req_way;	// ventus/src/L2cache/SourceD.scala:42:7, :81:18
  assign io_bs_wadr_bits_set = s1_req_set;	// ventus/src/L2cache/SourceD.scala:42:7, :81:18
  assign io_bs_wadr_bits_mask = _write_sent_T ? io_pb_beat_mask : pb_beat_reg_mask;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:42:7, :66:26, :80:19
  assign io_bs_wdat_data = _write_sent_T ? io_pb_beat_data : pb_beat_reg_data;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, ventus/src/L2cache/SourceD.scala:42:7, :66:26, :80:19
  assign io_a_valid = io_a_valid_0;	// ventus/src/L2cache/SourceD.scala:42:7, :274:86
  assign io_a_bits_size = s_final_req_size;	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
  assign io_a_bits_source = s_final_req_source;	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
  assign io_a_bits_tag = s_final_req_tag;	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
  assign io_a_bits_offset = s_final_req_offset;	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
  assign io_a_bits_put = s_final_req_put;	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
  assign io_a_bits_data =
    _io_a_bits_data_T | _io_a_bits_data_T_1 ? s_final_req_data : io_bs_rdat_data;	// ventus/src/L2cache/SourceD.scala:42:7, :82:26, :103:{140,178}, :277:{25,60}
  assign io_a_bits_mask = s_final_req_mask;	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
  assign io_a_bits_param = s_final_req_param;	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
  assign io_a_bits_set = s_final_req_set;	// ventus/src/L2cache/SourceD.scala:42:7, :82:26
  assign io_mshr_wait = mshr_wait_reg;	// ventus/src/L2cache/SourceD.scala:42:7, :128:27
  assign io_finish_issue = io_d_valid_0 & s_final_req_last_flush;	// ventus/src/L2cache/SourceD.scala:42:7, :82:26, :264:66, :280:33
endmodule

