// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TCDotProduct(	// dependencies/fpuv2/src/main/scala/Tensor.scala:87:7
  input         clock,	// dependencies/fpuv2/src/main/scala/Tensor.scala:87:7
                reset,	// dependencies/fpuv2/src/main/scala/Tensor.scala:87:7
  output        io_in_ready,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  input         io_in_valid,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  input  [31:0] io_in_bits_a_0,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_a_1,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_a_2,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_a_3,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_a_4,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_a_5,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_a_6,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_a_7,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_b_0,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_b_1,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_b_2,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_b_3,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_b_4,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_b_5,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_b_6,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_b_7,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_c,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  input  [2:0]  io_in_bits_rm,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  input  [4:0]  io_in_bits_ctrl_reg_idxw,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  input  [2:0]  io_in_bits_ctrl_warpID,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  input  [7:0]  io_in_bits_ctrl_spike_info_sm_id,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  input  [31:0] io_in_bits_ctrl_spike_info_pc,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_in_bits_ctrl_spike_info_inst,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  input         io_out_ready,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  output        io_out_valid,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  output [31:0] io_out_bits_result,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  output [4:0]  io_out_bits_ctrl_reg_idxw,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  output [2:0]  io_out_bits_ctrl_warpID,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  output [7:0]  io_out_bits_ctrl_spike_info_sm_id,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
  output [31:0] io_out_bits_ctrl_spike_info_pc,	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
                io_out_bits_ctrl_spike_info_inst	// dependencies/fpuv2/src/main/scala/Tensor.scala:92:14
);

  wire        _fifo_io_enq_ready;	// dependencies/fpuv2/src/main/scala/Tensor.scala:173:20
  wire        _finalAdd_io_in_ready;	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
  wire        _finalAdd_io_out_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
  wire [31:0] _finalAdd_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
  wire [4:0]  _finalAdd_io_out_bits_fflags;	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
  wire [4:0]  _finalAdd_io_out_bits_ctrl_ctrl_reg_idxw;	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
  wire [2:0]  _finalAdd_io_out_bits_ctrl_ctrl_warpID;	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
  wire [7:0]  _finalAdd_io_out_bits_ctrl_ctrl_spike_info_sm_id;	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
  wire [31:0] _finalAdd_io_out_bits_ctrl_ctrl_spike_info_pc;	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
  wire [31:0] _finalAdd_io_out_bits_ctrl_ctrl_spike_info_inst;	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
  wire        _adds_2_0_io_in_ready;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire        _adds_2_0_io_out_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _adds_2_0_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [2:0]  _adds_2_0_io_out_bits_ctrl_rm;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _adds_2_0_io_out_bits_ctrl_c;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [4:0]  _adds_2_0_io_out_bits_ctrl_ctrl_reg_idxw;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [2:0]  _adds_2_0_io_out_bits_ctrl_ctrl_warpID;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [7:0]  _adds_2_0_io_out_bits_ctrl_ctrl_spike_info_sm_id;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _adds_2_0_io_out_bits_ctrl_ctrl_spike_info_pc;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _adds_2_0_io_out_bits_ctrl_ctrl_spike_info_inst;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire        _adds_1_1_io_in_ready;	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
  wire [31:0] _adds_1_1_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
  wire        _adds_1_0_io_in_ready;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire        _adds_1_0_io_out_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _adds_1_0_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [2:0]  _adds_1_0_io_out_bits_ctrl_rm;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _adds_1_0_io_out_bits_ctrl_c;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [4:0]  _adds_1_0_io_out_bits_ctrl_ctrl_reg_idxw;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [2:0]  _adds_1_0_io_out_bits_ctrl_ctrl_warpID;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [7:0]  _adds_1_0_io_out_bits_ctrl_ctrl_spike_info_sm_id;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _adds_1_0_io_out_bits_ctrl_ctrl_spike_info_pc;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _adds_1_0_io_out_bits_ctrl_ctrl_spike_info_inst;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire        _adds_0_3_io_in_ready;	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
  wire [31:0] _adds_0_3_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
  wire        _adds_0_2_io_in_ready;	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
  wire [31:0] _adds_0_2_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
  wire        _adds_0_1_io_in_ready;	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
  wire        _adds_0_1_io_out_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
  wire [31:0] _adds_0_1_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
  wire        _adds_0_0_io_in_ready;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire        _adds_0_0_io_out_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _adds_0_0_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [2:0]  _adds_0_0_io_out_bits_ctrl_rm;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _adds_0_0_io_out_bits_ctrl_c;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [4:0]  _adds_0_0_io_out_bits_ctrl_ctrl_reg_idxw;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [2:0]  _adds_0_0_io_out_bits_ctrl_ctrl_warpID;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [7:0]  _adds_0_0_io_out_bits_ctrl_ctrl_spike_info_sm_id;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _adds_0_0_io_out_bits_ctrl_ctrl_spike_info_pc;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _adds_0_0_io_out_bits_ctrl_ctrl_spike_info_inst;	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
  wire [31:0] _muls_7_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
  wire [31:0] _muls_6_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
  wire [31:0] _muls_5_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
  wire [31:0] _muls_4_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
  wire        _muls_3_io_out_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
  wire [31:0] _muls_3_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
  wire        _muls_2_io_out_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
  wire [31:0] _muls_2_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
  wire        _muls_1_io_out_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
  wire [31:0] _muls_1_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
  wire        _muls_0_io_out_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
  wire [31:0] _muls_0_io_out_bits_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
  wire [2:0]  _muls_0_io_out_bits_ctrl_rm;	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
  wire [31:0] _muls_0_io_out_bits_ctrl_c;	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
  wire [4:0]  _muls_0_io_out_bits_ctrl_ctrl_reg_idxw;	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
  wire [2:0]  _muls_0_io_out_bits_ctrl_ctrl_warpID;	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
  wire [7:0]  _muls_0_io_out_bits_ctrl_ctrl_spike_info_sm_id;	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
  wire [31:0] _muls_0_io_out_bits_ctrl_ctrl_spike_info_pc;	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
  wire [31:0] _muls_0_io_out_bits_ctrl_ctrl_spike_info_inst;	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
  TCMulPipe muls_0 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .clock                                  (clock),
    .reset                                  (reset),
    .io_in_valid                            (io_in_valid),
    .io_in_bits_a                           (io_in_bits_a_0),
    .io_in_bits_b                           (io_in_bits_b_0),
    .io_in_bits_rm                          (io_in_bits_rm),
    .io_in_bits_ctrl_rm                     (io_in_bits_rm),
    .io_in_bits_ctrl_c                      (io_in_bits_c),
    .io_in_bits_ctrl_ctrl_reg_idxw          (io_in_bits_ctrl_reg_idxw),
    .io_in_bits_ctrl_ctrl_warpID            (io_in_bits_ctrl_warpID),
    .io_in_bits_ctrl_ctrl_spike_info_sm_id  (io_in_bits_ctrl_spike_info_sm_id),
    .io_in_bits_ctrl_ctrl_spike_info_pc     (io_in_bits_ctrl_spike_info_pc),
    .io_in_bits_ctrl_ctrl_spike_info_inst   (io_in_bits_ctrl_spike_info_inst),
    .io_out_ready                           (_adds_0_0_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_out_valid                           (_muls_0_io_out_valid),
    .io_out_bits_result                     (_muls_0_io_out_bits_result),
    .io_out_bits_ctrl_rm                    (_muls_0_io_out_bits_ctrl_rm),
    .io_out_bits_ctrl_c                     (_muls_0_io_out_bits_ctrl_c),
    .io_out_bits_ctrl_ctrl_reg_idxw         (_muls_0_io_out_bits_ctrl_ctrl_reg_idxw),
    .io_out_bits_ctrl_ctrl_warpID           (_muls_0_io_out_bits_ctrl_ctrl_warpID),
    .io_out_bits_ctrl_ctrl_spike_info_sm_id
      (_muls_0_io_out_bits_ctrl_ctrl_spike_info_sm_id),
    .io_out_bits_ctrl_ctrl_spike_info_pc    (_muls_0_io_out_bits_ctrl_ctrl_spike_info_pc),
    .io_out_bits_ctrl_ctrl_spike_info_inst
      (_muls_0_io_out_bits_ctrl_ctrl_spike_info_inst)
  );
  TCMulPipe_1 muls_1 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (/* unused */),
    .io_in_valid        (io_in_valid),
    .io_in_bits_a       (io_in_bits_a_1),
    .io_in_bits_b       (io_in_bits_b_1),
    .io_in_bits_rm      (io_in_bits_rm),
    .io_out_ready       (_adds_0_1_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_out_valid       (_muls_1_io_out_valid),
    .io_out_bits_result (_muls_1_io_out_bits_result)
  );
  TCMulPipe_1 muls_2 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (/* unused */),
    .io_in_valid        (io_in_valid),
    .io_in_bits_a       (io_in_bits_a_2),
    .io_in_bits_b       (io_in_bits_b_2),
    .io_in_bits_rm      (io_in_bits_rm),
    .io_out_ready       (_adds_0_2_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_out_valid       (_muls_2_io_out_valid),
    .io_out_bits_result (_muls_2_io_out_bits_result)
  );
  TCMulPipe_1 muls_3 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (/* unused */),
    .io_in_valid        (io_in_valid),
    .io_in_bits_a       (io_in_bits_a_3),
    .io_in_bits_b       (io_in_bits_b_3),
    .io_in_bits_rm      (io_in_bits_rm),
    .io_out_ready       (_adds_0_3_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_out_valid       (_muls_3_io_out_valid),
    .io_out_bits_result (_muls_3_io_out_bits_result)
  );
  TCMulPipe_1 muls_4 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (/* unused */),
    .io_in_valid        (io_in_valid),
    .io_in_bits_a       (io_in_bits_a_4),
    .io_in_bits_b       (io_in_bits_b_4),
    .io_in_bits_rm      (io_in_bits_rm),
    .io_out_ready       (_adds_0_0_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_out_valid       (/* unused */),
    .io_out_bits_result (_muls_4_io_out_bits_result)
  );
  TCMulPipe_1 muls_5 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (/* unused */),
    .io_in_valid        (io_in_valid),
    .io_in_bits_a       (io_in_bits_a_5),
    .io_in_bits_b       (io_in_bits_b_5),
    .io_in_bits_rm      (io_in_bits_rm),
    .io_out_ready       (_adds_0_1_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_out_valid       (/* unused */),
    .io_out_bits_result (_muls_5_io_out_bits_result)
  );
  TCMulPipe_1 muls_6 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (/* unused */),
    .io_in_valid        (io_in_valid),
    .io_in_bits_a       (io_in_bits_a_6),
    .io_in_bits_b       (io_in_bits_b_6),
    .io_in_bits_rm      (io_in_bits_rm),
    .io_out_ready       (_adds_0_2_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_out_valid       (/* unused */),
    .io_out_bits_result (_muls_6_io_out_bits_result)
  );
  TCMulPipe_1 muls_7 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (io_in_ready),
    .io_in_valid        (io_in_valid),
    .io_in_bits_a       (io_in_bits_a_7),
    .io_in_bits_b       (io_in_bits_b_7),
    .io_in_bits_rm      (io_in_bits_rm),
    .io_out_ready       (_adds_0_3_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_out_valid       (/* unused */),
    .io_out_bits_result (_muls_7_io_out_bits_result)
  );
  TCAddPipe adds_0_0 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .clock                                  (clock),
    .reset                                  (reset),
    .io_in_ready                            (_adds_0_0_io_in_ready),
    .io_in_valid                            (_muls_0_io_out_valid),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_in_bits_a                           (_muls_0_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_in_bits_b                           (_muls_4_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .io_in_bits_rm                          (_muls_0_io_out_bits_ctrl_rm),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_in_bits_ctrl_rm                     (_muls_0_io_out_bits_ctrl_rm),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_in_bits_ctrl_c                      (_muls_0_io_out_bits_ctrl_c),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_in_bits_ctrl_ctrl_reg_idxw          (_muls_0_io_out_bits_ctrl_ctrl_reg_idxw),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_in_bits_ctrl_ctrl_warpID            (_muls_0_io_out_bits_ctrl_ctrl_warpID),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_in_bits_ctrl_ctrl_spike_info_sm_id
      (_muls_0_io_out_bits_ctrl_ctrl_spike_info_sm_id),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_in_bits_ctrl_ctrl_spike_info_pc     (_muls_0_io_out_bits_ctrl_ctrl_spike_info_pc),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_in_bits_ctrl_ctrl_spike_info_inst
      (_muls_0_io_out_bits_ctrl_ctrl_spike_info_inst),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_out_ready                           (_adds_1_0_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_out_valid                           (_adds_0_0_io_out_valid),
    .io_out_bits_result                     (_adds_0_0_io_out_bits_result),
    .io_out_bits_fflags                     (/* unused */),
    .io_out_bits_ctrl_rm                    (_adds_0_0_io_out_bits_ctrl_rm),
    .io_out_bits_ctrl_c                     (_adds_0_0_io_out_bits_ctrl_c),
    .io_out_bits_ctrl_ctrl_reg_idxw         (_adds_0_0_io_out_bits_ctrl_ctrl_reg_idxw),
    .io_out_bits_ctrl_ctrl_warpID           (_adds_0_0_io_out_bits_ctrl_ctrl_warpID),
    .io_out_bits_ctrl_ctrl_spike_info_sm_id
      (_adds_0_0_io_out_bits_ctrl_ctrl_spike_info_sm_id),
    .io_out_bits_ctrl_ctrl_spike_info_pc
      (_adds_0_0_io_out_bits_ctrl_ctrl_spike_info_pc),
    .io_out_bits_ctrl_ctrl_spike_info_inst
      (_adds_0_0_io_out_bits_ctrl_ctrl_spike_info_inst)
  );
  TCAddPipe_1 adds_0_1 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (_adds_0_1_io_in_ready),
    .io_in_valid        (_muls_1_io_out_valid),	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .io_in_bits_a       (_muls_1_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .io_in_bits_b       (_muls_5_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .io_in_bits_rm      (_muls_0_io_out_bits_ctrl_rm),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_out_ready       (_adds_1_1_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_out_valid       (_adds_0_1_io_out_valid),
    .io_out_bits_result (_adds_0_1_io_out_bits_result)
  );
  TCAddPipe_1 adds_0_2 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (_adds_0_2_io_in_ready),
    .io_in_valid        (_muls_2_io_out_valid),	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .io_in_bits_a       (_muls_2_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .io_in_bits_b       (_muls_6_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .io_in_bits_rm      (_muls_0_io_out_bits_ctrl_rm),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_out_ready       (_adds_1_0_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_out_valid       (/* unused */),
    .io_out_bits_result (_adds_0_2_io_out_bits_result)
  );
  TCAddPipe_1 adds_0_3 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (_adds_0_3_io_in_ready),
    .io_in_valid        (_muls_3_io_out_valid),	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .io_in_bits_a       (_muls_3_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .io_in_bits_b       (_muls_7_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:109:30
    .io_in_bits_rm      (_muls_0_io_out_bits_ctrl_rm),	// dependencies/fpuv2/src/main/scala/Tensor.scala:108:24
    .io_out_ready       (_adds_1_1_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_out_valid       (/* unused */),
    .io_out_bits_result (_adds_0_3_io_out_bits_result)
  );
  TCAddPipe adds_1_0 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .clock                                  (clock),
    .reset                                  (reset),
    .io_in_ready                            (_adds_1_0_io_in_ready),
    .io_in_valid                            (_adds_0_0_io_out_valid),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_a                           (_adds_0_0_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_b                           (_adds_0_2_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_in_bits_rm                          (_adds_0_0_io_out_bits_ctrl_rm),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_rm                     (_adds_0_0_io_out_bits_ctrl_rm),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_c                      (_adds_0_0_io_out_bits_ctrl_c),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_reg_idxw          (_adds_0_0_io_out_bits_ctrl_ctrl_reg_idxw),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_warpID            (_adds_0_0_io_out_bits_ctrl_ctrl_warpID),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_spike_info_sm_id
      (_adds_0_0_io_out_bits_ctrl_ctrl_spike_info_sm_id),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_spike_info_pc
      (_adds_0_0_io_out_bits_ctrl_ctrl_spike_info_pc),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_spike_info_inst
      (_adds_0_0_io_out_bits_ctrl_ctrl_spike_info_inst),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_out_ready                           (_adds_2_0_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_out_valid                           (_adds_1_0_io_out_valid),
    .io_out_bits_result                     (_adds_1_0_io_out_bits_result),
    .io_out_bits_fflags                     (/* unused */),
    .io_out_bits_ctrl_rm                    (_adds_1_0_io_out_bits_ctrl_rm),
    .io_out_bits_ctrl_c                     (_adds_1_0_io_out_bits_ctrl_c),
    .io_out_bits_ctrl_ctrl_reg_idxw         (_adds_1_0_io_out_bits_ctrl_ctrl_reg_idxw),
    .io_out_bits_ctrl_ctrl_warpID           (_adds_1_0_io_out_bits_ctrl_ctrl_warpID),
    .io_out_bits_ctrl_ctrl_spike_info_sm_id
      (_adds_1_0_io_out_bits_ctrl_ctrl_spike_info_sm_id),
    .io_out_bits_ctrl_ctrl_spike_info_pc
      (_adds_1_0_io_out_bits_ctrl_ctrl_spike_info_pc),
    .io_out_bits_ctrl_ctrl_spike_info_inst
      (_adds_1_0_io_out_bits_ctrl_ctrl_spike_info_inst)
  );
  TCAddPipe_1 adds_1_1 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (_adds_1_1_io_in_ready),
    .io_in_valid        (_adds_0_1_io_out_valid),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_in_bits_a       (_adds_0_1_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_in_bits_b       (_adds_0_3_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_in_bits_rm      (_adds_0_0_io_out_bits_ctrl_rm),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_out_ready       (_adds_2_0_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_out_valid       (/* unused */),
    .io_out_bits_result (_adds_1_1_io_out_bits_result)
  );
  TCAddPipe adds_2_0 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .clock                                  (clock),
    .reset                                  (reset),
    .io_in_ready                            (_adds_2_0_io_in_ready),
    .io_in_valid                            (_adds_1_0_io_out_valid),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_a                           (_adds_1_0_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_b                           (_adds_1_1_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:103:32
    .io_in_bits_rm                          (_adds_1_0_io_out_bits_ctrl_rm),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_rm                     (_adds_1_0_io_out_bits_ctrl_rm),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_c                      (_adds_1_0_io_out_bits_ctrl_c),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_reg_idxw          (_adds_1_0_io_out_bits_ctrl_ctrl_reg_idxw),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_warpID            (_adds_1_0_io_out_bits_ctrl_ctrl_warpID),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_spike_info_sm_id
      (_adds_1_0_io_out_bits_ctrl_ctrl_spike_info_sm_id),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_spike_info_pc
      (_adds_1_0_io_out_bits_ctrl_ctrl_spike_info_pc),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_spike_info_inst
      (_adds_1_0_io_out_bits_ctrl_ctrl_spike_info_inst),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_out_ready                           (_finalAdd_io_in_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
    .io_out_valid                           (_adds_2_0_io_out_valid),
    .io_out_bits_result                     (_adds_2_0_io_out_bits_result),
    .io_out_bits_fflags                     (/* unused */),
    .io_out_bits_ctrl_rm                    (_adds_2_0_io_out_bits_ctrl_rm),
    .io_out_bits_ctrl_c                     (_adds_2_0_io_out_bits_ctrl_c),
    .io_out_bits_ctrl_ctrl_reg_idxw         (_adds_2_0_io_out_bits_ctrl_ctrl_reg_idxw),
    .io_out_bits_ctrl_ctrl_warpID           (_adds_2_0_io_out_bits_ctrl_ctrl_warpID),
    .io_out_bits_ctrl_ctrl_spike_info_sm_id
      (_adds_2_0_io_out_bits_ctrl_ctrl_spike_info_sm_id),
    .io_out_bits_ctrl_ctrl_spike_info_pc
      (_adds_2_0_io_out_bits_ctrl_ctrl_spike_info_pc),
    .io_out_bits_ctrl_ctrl_spike_info_inst
      (_adds_2_0_io_out_bits_ctrl_ctrl_spike_info_inst)
  );
  TCAddPipe finalAdd (	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
    .clock                                  (clock),
    .reset                                  (reset),
    .io_in_ready                            (_finalAdd_io_in_ready),
    .io_in_valid                            (_adds_2_0_io_out_valid),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_a                           (_adds_2_0_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_b                           (_adds_2_0_io_out_bits_ctrl_c),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_rm                          (_adds_2_0_io_out_bits_ctrl_rm),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_rm                     (_adds_2_0_io_out_bits_ctrl_rm),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_c                      (_adds_2_0_io_out_bits_ctrl_c),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_reg_idxw          (_adds_2_0_io_out_bits_ctrl_ctrl_reg_idxw),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_warpID            (_adds_2_0_io_out_bits_ctrl_ctrl_warpID),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_spike_info_sm_id
      (_adds_2_0_io_out_bits_ctrl_ctrl_spike_info_sm_id),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_spike_info_pc
      (_adds_2_0_io_out_bits_ctrl_ctrl_spike_info_pc),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_in_bits_ctrl_ctrl_spike_info_inst
      (_adds_2_0_io_out_bits_ctrl_ctrl_spike_info_inst),	// dependencies/fpuv2/src/main/scala/Tensor.scala:102:32
    .io_out_ready                           (_fifo_io_enq_ready),	// dependencies/fpuv2/src/main/scala/Tensor.scala:173:20
    .io_out_valid                           (_finalAdd_io_out_valid),
    .io_out_bits_result                     (_finalAdd_io_out_bits_result),
    .io_out_bits_fflags                     (_finalAdd_io_out_bits_fflags),
    .io_out_bits_ctrl_rm                    (/* unused */),
    .io_out_bits_ctrl_c                     (/* unused */),
    .io_out_bits_ctrl_ctrl_reg_idxw         (_finalAdd_io_out_bits_ctrl_ctrl_reg_idxw),
    .io_out_bits_ctrl_ctrl_warpID           (_finalAdd_io_out_bits_ctrl_ctrl_warpID),
    .io_out_bits_ctrl_ctrl_spike_info_sm_id
      (_finalAdd_io_out_bits_ctrl_ctrl_spike_info_sm_id),
    .io_out_bits_ctrl_ctrl_spike_info_pc
      (_finalAdd_io_out_bits_ctrl_ctrl_spike_info_pc),
    .io_out_bits_ctrl_ctrl_spike_info_inst
      (_finalAdd_io_out_bits_ctrl_ctrl_spike_info_inst)
  );
  Queue1_TCDotProductOutput fifo (	// dependencies/fpuv2/src/main/scala/Tensor.scala:173:20
    .clock                             (clock),
    .reset                             (reset),
    .io_enq_ready                      (_fifo_io_enq_ready),
    .io_enq_valid                      (_finalAdd_io_out_valid),	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
    .io_enq_bits_result                (_finalAdd_io_out_bits_result),	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
    .io_enq_bits_fflags                (_finalAdd_io_out_bits_fflags),	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
    .io_enq_bits_ctrl_reg_idxw         (_finalAdd_io_out_bits_ctrl_ctrl_reg_idxw),	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
    .io_enq_bits_ctrl_warpID           (_finalAdd_io_out_bits_ctrl_ctrl_warpID),	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
    .io_enq_bits_ctrl_spike_info_sm_id (_finalAdd_io_out_bits_ctrl_ctrl_spike_info_sm_id),	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
    .io_enq_bits_ctrl_spike_info_pc    (_finalAdd_io_out_bits_ctrl_ctrl_spike_info_pc),	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
    .io_enq_bits_ctrl_spike_info_inst  (_finalAdd_io_out_bits_ctrl_ctrl_spike_info_inst),	// dependencies/fpuv2/src/main/scala/Tensor.scala:161:24
    .io_deq_ready                      (io_out_ready),
    .io_deq_valid                      (io_out_valid),
    .io_deq_bits_result                (io_out_bits_result),
    .io_deq_bits_ctrl_reg_idxw         (io_out_bits_ctrl_reg_idxw),
    .io_deq_bits_ctrl_warpID           (io_out_bits_ctrl_warpID),
    .io_deq_bits_ctrl_spike_info_sm_id (io_out_bits_ctrl_spike_info_sm_id),
    .io_deq_bits_ctrl_spike_info_pc    (io_out_bits_ctrl_spike_info_pc),
    .io_deq_bits_ctrl_spike_info_inst  (io_out_bits_ctrl_spike_info_inst)
  );
endmodule

