// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TCMulPipe_4(	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
  input         clock,	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
                reset,	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
                io_in_valid,	// dependencies/fpuv2/src/main/scala/utils/FPUSubModule.scala:70:14
  input  [31:0] io_in_bits_a,	// dependencies/fpuv2/src/main/scala/utils/FPUSubModule.scala:70:14
                io_in_bits_b,	// dependencies/fpuv2/src/main/scala/utils/FPUSubModule.scala:70:14
  input  [2:0]  io_in_bits_rm,	// dependencies/fpuv2/src/main/scala/utils/FPUSubModule.scala:70:14
                io_in_bits_ctrl_rm,	// dependencies/fpuv2/src/main/scala/utils/FPUSubModule.scala:70:14
  input  [31:0] io_in_bits_ctrl_c,	// dependencies/fpuv2/src/main/scala/utils/FPUSubModule.scala:70:14
  input         io_out_ready,	// dependencies/fpuv2/src/main/scala/utils/FPUSubModule.scala:70:14
  output        io_out_valid,	// dependencies/fpuv2/src/main/scala/utils/FPUSubModule.scala:70:14
  output [31:0] io_out_bits_result,	// dependencies/fpuv2/src/main/scala/utils/FPUSubModule.scala:70:14
  output [2:0]  io_out_bits_ctrl_rm,	// dependencies/fpuv2/src/main/scala/utils/FPUSubModule.scala:70:14
  output [31:0] io_out_bits_ctrl_c	// dependencies/fpuv2/src/main/scala/utils/FPUSubModule.scala:70:14
);

  wire        _s2_io_out_special_case_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18
  wire        _s2_io_out_special_case_bits_nan;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18
  wire        _s2_io_out_special_case_bits_inf;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18
  wire        _s2_io_out_special_case_bits_inv;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18
  wire        _s2_io_out_special_case_bits_hasZero;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18
  wire        _s2_io_out_raw_out_sign;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18
  wire [8:0]  _s2_io_out_raw_out_exp;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18
  wire [73:0] _s2_io_out_raw_out_sig;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18
  wire        _s2_io_out_early_overflow;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18
  wire [2:0]  _s2_io_out_rm;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18
  wire        _s1_io_out_special_case_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18
  wire        _s1_io_out_special_case_bits_nan;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18
  wire        _s1_io_out_special_case_bits_inf;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18
  wire        _s1_io_out_special_case_bits_inv;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18
  wire        _s1_io_out_special_case_bits_hasZero;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18
  wire        _s1_io_out_early_overflow;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18
  wire        _s1_io_out_prod_sign;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18
  wire [8:0]  _s1_io_out_shift_amt;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18
  wire [8:0]  _s1_io_out_exp_shifted;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18
  wire        _s1_io_out_may_be_subnormal;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18
  wire [2:0]  _s1_io_out_rm;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18
  wire [49:0] _multiplier_io_result;	// dependencies/fpuv2/src/main/scala/Tensor.scala:39:26
  reg         REG;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58
  reg         REG_1;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58
  wire        _io_out_bits_ctrl_T_1 = REG & REG_1;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :18:53
  reg         s2_io_in_r_special_case_valid;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s2_io_in_r_special_case_bits_nan;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s2_io_in_r_special_case_bits_inf;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s2_io_in_r_special_case_bits_inv;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s2_io_in_r_special_case_bits_hasZero;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s2_io_in_r_early_overflow;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s2_io_in_r_prod_sign;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg  [8:0]  s2_io_in_r_shift_amt;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg  [8:0]  s2_io_in_r_exp_shifted;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s2_io_in_r_may_be_subnormal;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg  [2:0]  s2_io_in_r_rm;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s3_io_in_r_special_case_valid;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s3_io_in_r_special_case_bits_nan;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s3_io_in_r_special_case_bits_inf;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s3_io_in_r_special_case_bits_inv;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s3_io_in_r_special_case_bits_hasZero;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s3_io_in_r_raw_out_sign;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg  [8:0]  s3_io_in_r_raw_out_exp;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg  [73:0] s3_io_in_r_raw_out_sig;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg         s3_io_in_r_early_overflow;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg  [2:0]  s3_io_in_r_rm;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg  [2:0]  io_out_bits_ctrl_r_rm;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg  [31:0] io_out_bits_ctrl_r_c;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg  [2:0]  io_out_bits_ctrl_r_1_rm;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  reg  [31:0] io_out_bits_ctrl_r_1_c;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  always @(posedge clock) begin	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
    if (reset) begin	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
      REG <= 1'h0;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58
      REG_1 <= 1'h0;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58
    end
    else begin	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
      if (~(~io_out_ready & _io_out_bits_ctrl_T_1))	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:18:{12,26,53}
        REG <= io_in_valid;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58
      if (~(~io_out_ready & REG_1))	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :18:{12,26}
        REG_1 <= REG;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58
    end
    if (io_in_valid & ~(~io_out_ready & _io_out_bits_ctrl_T_1)) begin	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:18:{12,53}, :26:{79,82,98}
      s2_io_in_r_special_case_valid <= _s1_io_out_special_case_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s2_io_in_r_special_case_bits_nan <= _s1_io_out_special_case_bits_nan;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s2_io_in_r_special_case_bits_inf <= _s1_io_out_special_case_bits_inf;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s2_io_in_r_special_case_bits_inv <= _s1_io_out_special_case_bits_inv;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s2_io_in_r_special_case_bits_hasZero <= _s1_io_out_special_case_bits_hasZero;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s2_io_in_r_early_overflow <= _s1_io_out_early_overflow;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s2_io_in_r_prod_sign <= _s1_io_out_prod_sign;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s2_io_in_r_shift_amt <= _s1_io_out_shift_amt;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s2_io_in_r_exp_shifted <= _s1_io_out_exp_shifted;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s2_io_in_r_may_be_subnormal <= _s1_io_out_may_be_subnormal;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s2_io_in_r_rm <= _s1_io_out_rm;	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    end
    if (REG & ~(~io_out_ready & REG_1)) begin	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :18:12, :26:{79,82,98}
      s3_io_in_r_special_case_valid <= _s2_io_out_special_case_valid;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s3_io_in_r_special_case_bits_nan <= _s2_io_out_special_case_bits_nan;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s3_io_in_r_special_case_bits_inf <= _s2_io_out_special_case_bits_inf;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s3_io_in_r_special_case_bits_inv <= _s2_io_out_special_case_bits_inv;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s3_io_in_r_special_case_bits_hasZero <= _s2_io_out_special_case_bits_hasZero;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s3_io_in_r_raw_out_sign <= _s2_io_out_raw_out_sign;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s3_io_in_r_raw_out_exp <= _s2_io_out_raw_out_exp;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s3_io_in_r_raw_out_sig <= _s2_io_out_raw_out_sig;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s3_io_in_r_early_overflow <= _s2_io_out_early_overflow;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      s3_io_in_r_rm <= _s2_io_out_rm;	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    end
    if (io_in_valid & ~(~io_out_ready & _io_out_bits_ctrl_T_1)) begin	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:18:{12,53}, :26:{79,82,98}
      io_out_bits_ctrl_r_rm <= io_in_bits_ctrl_rm;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      io_out_bits_ctrl_r_c <= io_in_bits_ctrl_c;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    end
    if (REG & ~(~io_out_ready & REG_1)) begin	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :18:12, :26:{79,82,98}
      io_out_bits_ctrl_r_1_rm <= io_out_bits_ctrl_r_rm;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      io_out_bits_ctrl_r_1_c <= io_out_bits_ctrl_r_c;	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
    `ifdef FIRRTL_BEFORE_INITIAL	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
      `FIRRTL_BEFORE_INITIAL	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
      automatic logic [31:0] _RANDOM[0:6];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
      `ifdef INIT_RANDOM_PROLOG_	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
        `INIT_RANDOM_PROLOG_	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
        end	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
        REG = _RANDOM[3'h0][0];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58
        REG_1 = _RANDOM[3'h0][1];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58
        s2_io_in_r_special_case_valid = _RANDOM[3'h0][2];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :26:58
        s2_io_in_r_special_case_bits_nan = _RANDOM[3'h0][3];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :26:58
        s2_io_in_r_special_case_bits_inf = _RANDOM[3'h0][4];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :26:58
        s2_io_in_r_special_case_bits_inv = _RANDOM[3'h0][5];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :26:58
        s2_io_in_r_special_case_bits_hasZero = _RANDOM[3'h0][6];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :26:58
        s2_io_in_r_early_overflow = _RANDOM[3'h0][7];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :26:58
        s2_io_in_r_prod_sign = _RANDOM[3'h0][8];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :26:58
        s2_io_in_r_shift_amt = _RANDOM[3'h0][17:9];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :26:58
        s2_io_in_r_exp_shifted = _RANDOM[3'h0][26:18];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :26:58
        s2_io_in_r_may_be_subnormal = _RANDOM[3'h0][27];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :26:58
        s2_io_in_r_rm = _RANDOM[3'h0][30:28];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :26:58
        s3_io_in_r_special_case_valid = _RANDOM[3'h0][31];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58, :26:58
        s3_io_in_r_special_case_bits_nan = _RANDOM[3'h1][0];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
        s3_io_in_r_special_case_bits_inf = _RANDOM[3'h1][1];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
        s3_io_in_r_special_case_bits_inv = _RANDOM[3'h1][2];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
        s3_io_in_r_special_case_bits_hasZero = _RANDOM[3'h1][3];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
        s3_io_in_r_raw_out_sign = _RANDOM[3'h1][4];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
        s3_io_in_r_raw_out_exp = _RANDOM[3'h1][13:5];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
        s3_io_in_r_raw_out_sig =
          {_RANDOM[3'h1][31:14], _RANDOM[3'h2], _RANDOM[3'h3][23:0]};	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
        s3_io_in_r_early_overflow = _RANDOM[3'h3][24];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
        s3_io_in_r_rm = _RANDOM[3'h3][27:25];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
        io_out_bits_ctrl_r_rm = _RANDOM[3'h3][30:28];	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
        io_out_bits_ctrl_r_c = {_RANDOM[3'h3][31], _RANDOM[3'h4][30:0]};	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
        io_out_bits_ctrl_r_1_rm = {_RANDOM[3'h4][31], _RANDOM[3'h5][1:0]};	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
        io_out_bits_ctrl_r_1_c = {_RANDOM[3'h5][31:2], _RANDOM[3'h6][1:0]};	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
      `FIRRTL_AFTER_INITIAL	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  NaiveMultiplier multiplier (	// dependencies/fpuv2/src/main/scala/Tensor.scala:39:26
    .clock           (clock),
    .io_a            ({1'h0, |(io_in_bits_a[30:23]), io_in_bits_a[22:0]}),	// dependencies/fpuv2/fudian/src/main/scala/fudian/package.scala:60:18, :61:18, :81:69, dependencies/fpuv2/src/main/scala/Tensor.scala:56:19, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58
    .io_b            ({1'h0, |(io_in_bits_b[30:23]), io_in_bits_b[22:0]}),	// dependencies/fpuv2/fudian/src/main/scala/fudian/package.scala:60:18, :61:18, :81:69, dependencies/fpuv2/src/main/scala/Tensor.scala:57:19, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58
    .io_regEnables_0 (io_in_valid & ~(~io_out_ready & _io_out_bits_ctrl_T_1)),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:18:{12,53}, :23:{47,50,66}
    .io_result       (_multiplier_io_result)
  );
  FMUL_s1 s1 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:41:18
    .io_a                             (io_in_bits_a),
    .io_b                             (io_in_bits_b),
    .io_rm                            (io_in_bits_rm),
    .io_out_special_case_valid        (_s1_io_out_special_case_valid),
    .io_out_special_case_bits_nan     (_s1_io_out_special_case_bits_nan),
    .io_out_special_case_bits_inf     (_s1_io_out_special_case_bits_inf),
    .io_out_special_case_bits_inv     (_s1_io_out_special_case_bits_inv),
    .io_out_special_case_bits_hasZero (_s1_io_out_special_case_bits_hasZero),
    .io_out_early_overflow            (_s1_io_out_early_overflow),
    .io_out_prod_sign                 (_s1_io_out_prod_sign),
    .io_out_shift_amt                 (_s1_io_out_shift_amt),
    .io_out_exp_shifted               (_s1_io_out_exp_shifted),
    .io_out_may_be_subnormal          (_s1_io_out_may_be_subnormal),
    .io_out_rm                        (_s1_io_out_rm)
  );
  FMUL_s2 s2 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:42:18
    .io_in_special_case_valid         (s2_io_in_r_special_case_valid),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_special_case_bits_nan      (s2_io_in_r_special_case_bits_nan),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_special_case_bits_inf      (s2_io_in_r_special_case_bits_inf),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_special_case_bits_inv      (s2_io_in_r_special_case_bits_inv),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_special_case_bits_hasZero  (s2_io_in_r_special_case_bits_hasZero),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_early_overflow             (s2_io_in_r_early_overflow),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_prod_sign                  (s2_io_in_r_prod_sign),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_shift_amt                  (s2_io_in_r_shift_amt),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_exp_shifted                (s2_io_in_r_exp_shifted),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_may_be_subnormal           (s2_io_in_r_may_be_subnormal),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_rm                         (s2_io_in_r_rm),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_prod                          (_multiplier_io_result[47:0]),	// dependencies/fpuv2/src/main/scala/Tensor.scala:39:26, :50:14
    .io_out_special_case_valid        (_s2_io_out_special_case_valid),
    .io_out_special_case_bits_nan     (_s2_io_out_special_case_bits_nan),
    .io_out_special_case_bits_inf     (_s2_io_out_special_case_bits_inf),
    .io_out_special_case_bits_inv     (_s2_io_out_special_case_bits_inv),
    .io_out_special_case_bits_hasZero (_s2_io_out_special_case_bits_hasZero),
    .io_out_raw_out_sign              (_s2_io_out_raw_out_sign),
    .io_out_raw_out_exp               (_s2_io_out_raw_out_exp),
    .io_out_raw_out_sig               (_s2_io_out_raw_out_sig),
    .io_out_early_overflow            (_s2_io_out_early_overflow),
    .io_out_rm                        (_s2_io_out_rm)
  );
  FMUL_s3 s3 (	// dependencies/fpuv2/src/main/scala/Tensor.scala:43:18
    .io_in_special_case_valid        (s3_io_in_r_special_case_valid),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_special_case_bits_nan     (s3_io_in_r_special_case_bits_nan),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_special_case_bits_inf     (s3_io_in_r_special_case_bits_inf),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_special_case_bits_inv     (s3_io_in_r_special_case_bits_inv),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_special_case_bits_hasZero (s3_io_in_r_special_case_bits_hasZero),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_raw_out_sign              (s3_io_in_r_raw_out_sign),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_raw_out_exp               (s3_io_in_r_raw_out_exp),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_raw_out_sig               (s3_io_in_r_raw_out_sig),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_early_overflow            (s3_io_in_r_early_overflow),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_in_rm                        (s3_io_in_r_rm),	// dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
    .io_result                       (io_out_bits_result),
    .io_fflags                       (/* unused */),
    .io_to_fadd_fp_prod_sign         (/* unused */),
    .io_to_fadd_fp_prod_exp          (/* unused */),
    .io_to_fadd_fp_prod_sig          (/* unused */),
    .io_to_fadd_inter_flags_isNaN    (/* unused */),
    .io_to_fadd_inter_flags_isInf    (/* unused */),
    .io_to_fadd_inter_flags_isInv    (/* unused */),
    .io_to_fadd_inter_flags_overflow (/* unused */),
    .io_to_fadd_rm                   (/* unused */)
  );
  assign io_out_valid = REG_1;	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:16:58
  assign io_out_bits_ctrl_rm = io_out_bits_ctrl_r_1_rm;	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
  assign io_out_bits_ctrl_c = io_out_bits_ctrl_r_1_c;	// dependencies/fpuv2/src/main/scala/Tensor.scala:32:7, dependencies/fpuv2/src/main/scala/utils/HasPipelineReg.scala:26:58
endmodule

