// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module Queue1_vExeData_1(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input         clock,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                reset,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  output        io_enq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits_in1_0,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_1,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_2,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_3,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_4,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_5,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_6,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_7,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_8,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_9,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_10,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_11,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_12,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_13,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_14,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_15,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_16,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_17,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_18,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_19,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_20,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_21,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_22,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_23,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_24,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_25,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_26,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_27,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_28,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_29,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_30,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in1_31,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_0,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_1,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_2,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_3,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_4,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_5,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_6,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_7,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_8,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_9,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_10,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_11,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_12,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_13,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_14,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_15,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_16,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_17,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_18,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_19,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_20,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_21,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_22,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_23,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_24,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_25,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_26,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_27,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_28,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_29,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_30,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in2_31,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_0,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_1,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_2,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_3,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_4,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_5,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_6,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_7,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_8,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_9,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_10,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_11,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_12,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_13,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_14,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_15,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_16,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_17,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_18,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_19,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_20,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_21,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_22,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_23,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_24,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_25,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_26,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_27,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_28,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_29,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_30,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_in3_31,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_enq_bits_mask_0,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_1,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_2,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_3,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_4,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_5,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_6,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_7,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_8,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_9,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_10,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_11,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_12,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_13,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_14,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_15,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_16,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_17,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_18,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_19,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_20,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_21,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_22,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_23,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_24,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_25,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_26,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_27,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_28,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_29,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_30,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_mask_31,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits_ctrl_inst,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [2:0]  io_enq_bits_ctrl_wid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_enq_bits_ctrl_fp,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [1:0]  io_enq_bits_ctrl_branch,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_enq_bits_ctrl_simt_stack,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_simt_stack_op,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_barrier,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [1:0]  io_enq_bits_ctrl_csr,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_enq_bits_ctrl_reverse,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [1:0]  io_enq_bits_ctrl_sel_alu2,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_sel_alu1,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_enq_bits_ctrl_isvec,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [1:0]  io_enq_bits_ctrl_sel_alu3,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_enq_bits_ctrl_mask,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [3:0]  io_enq_bits_ctrl_sel_imm,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [1:0]  io_enq_bits_ctrl_mem_whb,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_enq_bits_ctrl_mem_unsigned,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [5:0]  io_enq_bits_ctrl_alu_fn,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_enq_bits_ctrl_force_rm_rtz,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_is_vls12,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_mem,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_mul,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_tc,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_disable_mask,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_custom_signal_0,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [1:0]  io_enq_bits_ctrl_mem_cmd,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_mop,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [7:0]  io_enq_bits_ctrl_reg_idx1,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_reg_idx2,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_reg_idx3,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_reg_idxw,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_enq_bits_ctrl_wvd,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_fence,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_sfu,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_readmask,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_writemask,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_wxd,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits_ctrl_pc,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [6:0]  io_enq_bits_ctrl_imm_ext,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [7:0]  io_enq_bits_ctrl_spike_info_sm_id,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits_ctrl_spike_info_pc,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_spike_info_inst,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_enq_bits_ctrl_atomic,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_aq,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_enq_bits_ctrl_rl,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits_in1_0,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_1,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_2,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_3,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_4,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_5,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_6,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_7,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_8,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_9,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_10,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_11,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_12,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_13,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_14,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_15,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_16,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_17,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_18,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_19,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_20,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_21,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_22,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_23,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_24,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_25,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_26,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_27,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_28,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_29,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_30,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in1_31,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_0,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_1,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_2,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_3,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_4,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_5,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_6,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_7,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_8,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_9,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_10,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_11,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_12,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_13,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_14,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_15,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_16,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_17,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_18,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_19,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_20,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_21,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_22,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_23,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_24,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_25,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_26,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_27,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_28,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_29,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_30,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_in2_31,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output        io_deq_bits_mask_0,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_1,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_2,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_3,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_4,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_5,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_6,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_7,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_8,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_9,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_10,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_11,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_12,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_13,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_14,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_15,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_16,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_17,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_18,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_19,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_20,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_21,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_22,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_23,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_24,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_25,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_26,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_27,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_28,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_29,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_30,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_mask_31,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [2:0]  io_deq_bits_ctrl_wid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output        io_deq_bits_ctrl_fp,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_ctrl_reverse,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_ctrl_isvec,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [5:0]  io_deq_bits_ctrl_alu_fn,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [7:0]  io_deq_bits_ctrl_reg_idxw,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output        io_deq_bits_ctrl_wvd,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_ctrl_wxd,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [7:0]  io_deq_bits_ctrl_spike_info_sm_id,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits_ctrl_spike_info_pc,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
                io_deq_bits_ctrl_spike_info_inst	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  reg [3331:0] ram;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  reg          full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    automatic logic do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    do_enq = ~full & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :286:19
    if (do_enq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      ram <=
        {io_enq_bits_ctrl_rl,
         io_enq_bits_ctrl_aq,
         io_enq_bits_ctrl_atomic,
         io_enq_bits_ctrl_spike_info_inst,
         io_enq_bits_ctrl_spike_info_pc,
         io_enq_bits_ctrl_spike_info_sm_id,
         io_enq_bits_ctrl_imm_ext,
         io_enq_bits_ctrl_pc,
         io_enq_bits_ctrl_wxd,
         io_enq_bits_ctrl_writemask,
         io_enq_bits_ctrl_readmask,
         io_enq_bits_ctrl_sfu,
         io_enq_bits_ctrl_fence,
         io_enq_bits_ctrl_wvd,
         io_enq_bits_ctrl_reg_idxw,
         io_enq_bits_ctrl_reg_idx3,
         io_enq_bits_ctrl_reg_idx2,
         io_enq_bits_ctrl_reg_idx1,
         io_enq_bits_ctrl_mop,
         io_enq_bits_ctrl_mem_cmd,
         io_enq_bits_ctrl_custom_signal_0,
         io_enq_bits_ctrl_disable_mask,
         io_enq_bits_ctrl_tc,
         io_enq_bits_ctrl_mul,
         io_enq_bits_ctrl_mem,
         io_enq_bits_ctrl_is_vls12,
         io_enq_bits_ctrl_force_rm_rtz,
         io_enq_bits_ctrl_alu_fn,
         io_enq_bits_ctrl_mem_unsigned,
         io_enq_bits_ctrl_mem_whb,
         io_enq_bits_ctrl_sel_imm,
         io_enq_bits_ctrl_mask,
         io_enq_bits_ctrl_sel_alu3,
         io_enq_bits_ctrl_isvec,
         io_enq_bits_ctrl_sel_alu1,
         io_enq_bits_ctrl_sel_alu2,
         io_enq_bits_ctrl_reverse,
         io_enq_bits_ctrl_csr,
         io_enq_bits_ctrl_barrier,
         io_enq_bits_ctrl_simt_stack_op,
         io_enq_bits_ctrl_simt_stack,
         io_enq_bits_ctrl_branch,
         io_enq_bits_ctrl_fp,
         io_enq_bits_ctrl_wid,
         io_enq_bits_ctrl_inst,
         io_enq_bits_mask_31,
         io_enq_bits_mask_30,
         io_enq_bits_mask_29,
         io_enq_bits_mask_28,
         io_enq_bits_mask_27,
         io_enq_bits_mask_26,
         io_enq_bits_mask_25,
         io_enq_bits_mask_24,
         io_enq_bits_mask_23,
         io_enq_bits_mask_22,
         io_enq_bits_mask_21,
         io_enq_bits_mask_20,
         io_enq_bits_mask_19,
         io_enq_bits_mask_18,
         io_enq_bits_mask_17,
         io_enq_bits_mask_16,
         io_enq_bits_mask_15,
         io_enq_bits_mask_14,
         io_enq_bits_mask_13,
         io_enq_bits_mask_12,
         io_enq_bits_mask_11,
         io_enq_bits_mask_10,
         io_enq_bits_mask_9,
         io_enq_bits_mask_8,
         io_enq_bits_mask_7,
         io_enq_bits_mask_6,
         io_enq_bits_mask_5,
         io_enq_bits_mask_4,
         io_enq_bits_mask_3,
         io_enq_bits_mask_2,
         io_enq_bits_mask_1,
         io_enq_bits_mask_0,
         io_enq_bits_in3_31,
         io_enq_bits_in3_30,
         io_enq_bits_in3_29,
         io_enq_bits_in3_28,
         io_enq_bits_in3_27,
         io_enq_bits_in3_26,
         io_enq_bits_in3_25,
         io_enq_bits_in3_24,
         io_enq_bits_in3_23,
         io_enq_bits_in3_22,
         io_enq_bits_in3_21,
         io_enq_bits_in3_20,
         io_enq_bits_in3_19,
         io_enq_bits_in3_18,
         io_enq_bits_in3_17,
         io_enq_bits_in3_16,
         io_enq_bits_in3_15,
         io_enq_bits_in3_14,
         io_enq_bits_in3_13,
         io_enq_bits_in3_12,
         io_enq_bits_in3_11,
         io_enq_bits_in3_10,
         io_enq_bits_in3_9,
         io_enq_bits_in3_8,
         io_enq_bits_in3_7,
         io_enq_bits_in3_6,
         io_enq_bits_in3_5,
         io_enq_bits_in3_4,
         io_enq_bits_in3_3,
         io_enq_bits_in3_2,
         io_enq_bits_in3_1,
         io_enq_bits_in3_0,
         io_enq_bits_in2_31,
         io_enq_bits_in2_30,
         io_enq_bits_in2_29,
         io_enq_bits_in2_28,
         io_enq_bits_in2_27,
         io_enq_bits_in2_26,
         io_enq_bits_in2_25,
         io_enq_bits_in2_24,
         io_enq_bits_in2_23,
         io_enq_bits_in2_22,
         io_enq_bits_in2_21,
         io_enq_bits_in2_20,
         io_enq_bits_in2_19,
         io_enq_bits_in2_18,
         io_enq_bits_in2_17,
         io_enq_bits_in2_16,
         io_enq_bits_in2_15,
         io_enq_bits_in2_14,
         io_enq_bits_in2_13,
         io_enq_bits_in2_12,
         io_enq_bits_in2_11,
         io_enq_bits_in2_10,
         io_enq_bits_in2_9,
         io_enq_bits_in2_8,
         io_enq_bits_in2_7,
         io_enq_bits_in2_6,
         io_enq_bits_in2_5,
         io_enq_bits_in2_4,
         io_enq_bits_in2_3,
         io_enq_bits_in2_2,
         io_enq_bits_in2_1,
         io_enq_bits_in2_0,
         io_enq_bits_in1_31,
         io_enq_bits_in1_30,
         io_enq_bits_in1_29,
         io_enq_bits_in1_28,
         io_enq_bits_in1_27,
         io_enq_bits_in1_26,
         io_enq_bits_in1_25,
         io_enq_bits_in1_24,
         io_enq_bits_in1_23,
         io_enq_bits_in1_22,
         io_enq_bits_in1_21,
         io_enq_bits_in1_20,
         io_enq_bits_in1_19,
         io_enq_bits_in1_18,
         io_enq_bits_in1_17,
         io_enq_bits_in1_16,
         io_enq_bits_in1_15,
         io_enq_bits_in1_14,
         io_enq_bits_in1_13,
         io_enq_bits_in1_12,
         io_enq_bits_in1_11,
         io_enq_bits_in1_10,
         io_enq_bits_in1_9,
         io_enq_bits_in1_8,
         io_enq_bits_in1_7,
         io_enq_bits_in1_6,
         io_enq_bits_in1_5,
         io_enq_bits_in1_4,
         io_enq_bits_in1_3,
         io_enq_bits_in1_2,
         io_enq_bits_in1_1,
         io_enq_bits_in1_0};	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (reset)	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    else if (~(do_enq == (io_deq_ready & full)))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
      full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:104];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        for (logic [6:0] i = 7'h0; i < 7'h69; i += 7'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        end	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        ram =
          {_RANDOM[7'h0][31:1],
           _RANDOM[7'h1],
           _RANDOM[7'h2],
           _RANDOM[7'h3],
           _RANDOM[7'h4],
           _RANDOM[7'h5],
           _RANDOM[7'h6],
           _RANDOM[7'h7],
           _RANDOM[7'h8],
           _RANDOM[7'h9],
           _RANDOM[7'hA],
           _RANDOM[7'hB],
           _RANDOM[7'hC],
           _RANDOM[7'hD],
           _RANDOM[7'hE],
           _RANDOM[7'hF],
           _RANDOM[7'h10],
           _RANDOM[7'h11],
           _RANDOM[7'h12],
           _RANDOM[7'h13],
           _RANDOM[7'h14],
           _RANDOM[7'h15],
           _RANDOM[7'h16],
           _RANDOM[7'h17],
           _RANDOM[7'h18],
           _RANDOM[7'h19],
           _RANDOM[7'h1A],
           _RANDOM[7'h1B],
           _RANDOM[7'h1C],
           _RANDOM[7'h1D],
           _RANDOM[7'h1E],
           _RANDOM[7'h1F],
           _RANDOM[7'h20],
           _RANDOM[7'h21],
           _RANDOM[7'h22],
           _RANDOM[7'h23],
           _RANDOM[7'h24],
           _RANDOM[7'h25],
           _RANDOM[7'h26],
           _RANDOM[7'h27],
           _RANDOM[7'h28],
           _RANDOM[7'h29],
           _RANDOM[7'h2A],
           _RANDOM[7'h2B],
           _RANDOM[7'h2C],
           _RANDOM[7'h2D],
           _RANDOM[7'h2E],
           _RANDOM[7'h2F],
           _RANDOM[7'h30],
           _RANDOM[7'h31],
           _RANDOM[7'h32],
           _RANDOM[7'h33],
           _RANDOM[7'h34],
           _RANDOM[7'h35],
           _RANDOM[7'h36],
           _RANDOM[7'h37],
           _RANDOM[7'h38],
           _RANDOM[7'h39],
           _RANDOM[7'h3A],
           _RANDOM[7'h3B],
           _RANDOM[7'h3C],
           _RANDOM[7'h3D],
           _RANDOM[7'h3E],
           _RANDOM[7'h3F],
           _RANDOM[7'h40],
           _RANDOM[7'h41],
           _RANDOM[7'h42],
           _RANDOM[7'h43],
           _RANDOM[7'h44],
           _RANDOM[7'h45],
           _RANDOM[7'h46],
           _RANDOM[7'h47],
           _RANDOM[7'h48],
           _RANDOM[7'h49],
           _RANDOM[7'h4A],
           _RANDOM[7'h4B],
           _RANDOM[7'h4C],
           _RANDOM[7'h4D],
           _RANDOM[7'h4E],
           _RANDOM[7'h4F],
           _RANDOM[7'h50],
           _RANDOM[7'h51],
           _RANDOM[7'h52],
           _RANDOM[7'h53],
           _RANDOM[7'h54],
           _RANDOM[7'h55],
           _RANDOM[7'h56],
           _RANDOM[7'h57],
           _RANDOM[7'h58],
           _RANDOM[7'h59],
           _RANDOM[7'h5A],
           _RANDOM[7'h5B],
           _RANDOM[7'h5C],
           _RANDOM[7'h5D],
           _RANDOM[7'h5E],
           _RANDOM[7'h5F],
           _RANDOM[7'h60],
           _RANDOM[7'h61],
           _RANDOM[7'h62],
           _RANDOM[7'h63],
           _RANDOM[7'h64],
           _RANDOM[7'h65],
           _RANDOM[7'h66],
           _RANDOM[7'h67],
           _RANDOM[7'h68][4:0]};	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
        full = _RANDOM[7'h0][0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = ~full;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27, :286:19
  assign io_deq_bits_in1_0 = ram[31:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_1 = ram[63:32];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_2 = ram[95:64];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_3 = ram[127:96];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_4 = ram[159:128];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_5 = ram[191:160];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_6 = ram[223:192];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_7 = ram[255:224];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_8 = ram[287:256];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_9 = ram[319:288];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_10 = ram[351:320];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_11 = ram[383:352];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_12 = ram[415:384];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_13 = ram[447:416];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_14 = ram[479:448];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_15 = ram[511:480];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_16 = ram[543:512];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_17 = ram[575:544];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_18 = ram[607:576];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_19 = ram[639:608];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_20 = ram[671:640];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_21 = ram[703:672];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_22 = ram[735:704];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_23 = ram[767:736];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_24 = ram[799:768];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_25 = ram[831:800];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_26 = ram[863:832];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_27 = ram[895:864];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_28 = ram[927:896];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_29 = ram[959:928];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_30 = ram[991:960];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in1_31 = ram[1023:992];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_0 = ram[1055:1024];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_1 = ram[1087:1056];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_2 = ram[1119:1088];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_3 = ram[1151:1120];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_4 = ram[1183:1152];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_5 = ram[1215:1184];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_6 = ram[1247:1216];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_7 = ram[1279:1248];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_8 = ram[1311:1280];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_9 = ram[1343:1312];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_10 = ram[1375:1344];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_11 = ram[1407:1376];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_12 = ram[1439:1408];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_13 = ram[1471:1440];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_14 = ram[1503:1472];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_15 = ram[1535:1504];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_16 = ram[1567:1536];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_17 = ram[1599:1568];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_18 = ram[1631:1600];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_19 = ram[1663:1632];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_20 = ram[1695:1664];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_21 = ram[1727:1696];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_22 = ram[1759:1728];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_23 = ram[1791:1760];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_24 = ram[1823:1792];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_25 = ram[1855:1824];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_26 = ram[1887:1856];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_27 = ram[1919:1888];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_28 = ram[1951:1920];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_29 = ram[1983:1952];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_30 = ram[2015:1984];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_in2_31 = ram[2047:2016];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_0 = ram[3072];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_1 = ram[3073];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_2 = ram[3074];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_3 = ram[3075];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_4 = ram[3076];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_5 = ram[3077];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_6 = ram[3078];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_7 = ram[3079];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_8 = ram[3080];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_9 = ram[3081];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_10 = ram[3082];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_11 = ram[3083];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_12 = ram[3084];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_13 = ram[3085];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_14 = ram[3086];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_15 = ram[3087];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_16 = ram[3088];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_17 = ram[3089];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_18 = ram[3090];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_19 = ram[3091];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_20 = ram[3092];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_21 = ram[3093];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_22 = ram[3094];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_23 = ram[3095];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_24 = ram[3096];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_25 = ram[3097];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_26 = ram[3098];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_27 = ram[3099];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_28 = ram[3100];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_29 = ram[3101];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_30 = ram[3102];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_mask_31 = ram[3103];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_ctrl_wid = ram[3138:3136];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_ctrl_fp = ram[3139];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_ctrl_reverse = ram[3147];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_ctrl_isvec = ram[3152];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_ctrl_alu_fn = ram[3168:3163];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_ctrl_reg_idxw = ram[3211:3204];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_ctrl_wvd = ram[3212];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_ctrl_wxd = ram[3217];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_ctrl_spike_info_sm_id = ram[3264:3257];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_ctrl_spike_info_pc = ram[3296:3265];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
  assign io_deq_bits_ctrl_spike_info_inst = ram[3328:3297];	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91
endmodule

